window.VOCAB_AUDIO_SETS = [
  {
    "id": "audio_1",
    "name": "音声用セット 1 (1 - 100)",
    "words": [
      { "en": "object", "ja": "反対する と言って反対する 節" },
      { "en": "describe", "ja": "について述べる を説明する" },
      { "en": "involve", "ja": "を関与させる を伴う" },
      { "en": "exist", "ja": "存在する 生存する" },
      { "en": "cause", "ja": "原因 理由 大義" },
      { "en": "matter", "ja": "事柄 問題 事態 困難 物質" },
      { "en": "role", "ja": "役割 俳優などの 役" },
      { "en": "public", "ja": "公の 私的な 公衆の 公開の" },
      { "en": "create", "ja": "を創り出す を引き起こす" },
      { "en": "increase", "ja": "増加する を増やす" },
      { "en": "improve", "ja": "を向上させる よくなる" },
      { "en": "mean", "ja": "を意味する する つもりである" },
      { "en": "own", "ja": "を所有している 事実 罪など を認める" },
      { "en": "include", "ja": "を含む" },
      { "en": "consider", "ja": "を見なす について考える" },
      { "en": "allow", "ja": "を許す を与える を 考慮に入れる" },
      { "en": "suggest", "ja": "を提案する を暗示する" },
      { "en": "produce", "ja": "を生産する を取り出す" },
      { "en": "decide", "ja": "を決める に決着をつける" },
      { "en": "offer", "ja": "を提供する 申し出る" },
      { "en": "require", "ja": "を要求する を必要とする" },
      { "en": "share", "ja": "を共有する を分担する" },
      { "en": "store", "ja": "を保存する を蓄える" },
      { "en": "tend", "ja": "傾向がある を世話する" },
      { "en": "concern", "ja": "受身形で 心配している 受身形で に 関係する に関連する" },
      { "en": "reduce", "ja": "を減らす を に 変える" },
      { "en": "design", "ja": "を設計する を計画する" },
      { "en": "force", "ja": "に強いる を強要する" },
      { "en": "limit", "ja": "を制限 規制 する" },
      { "en": "bear", "ja": "に耐える を負う を産む を 心に 抱く" },
      { "en": "affect", "ja": "に影響を及ぼす を感動させる" },
      { "en": "deal", "ja": "で を処理する で を商う を分配する" },
      { "en": "avoid", "ja": "を避ける" },
      { "en": "relate", "ja": "を関連づける に 関連する" },
      { "en": "realize", "ja": "に気づく を実現する" },
      { "en": "encourage", "ja": "を奨励する を励ます" },
      { "en": "compare", "ja": "を比較する を に たとえる" },
      { "en": "measure", "ja": "を測る を 比較して 評価する" },
      { "en": "mark", "ja": "に印をつける を 記号で 示す に汚れをつける" },
      { "en": "challenge", "ja": "に異議を唱える 人 に挑む" },
      { "en": "depend", "ja": "頼る 次第である" },
      { "en": "demand", "ja": "を要求する" },
      { "en": "found", "ja": "を設立する 理論など を に基づいて 築く" },
      { "en": "complete", "ja": "を完成させる 仕上げる" },
      { "en": "idea", "ja": "考え 思いつき 理解 見解 概念" },
      { "en": "accord", "ja": "一致 合意 協定" },
      { "en": "company", "ja": "会社 集合的に 仲間 仲間と 一緒にいること 一座" },
      { "en": "interest", "ja": "興味 利子 利害" },
      { "en": "research", "ja": "についての 研究 調査" },
      { "en": "reason", "ja": "理由 する 根拠 理性 分別" },
      { "en": "effect", "ja": "影響 効果 結果" },
      { "en": "influence", "ja": "影響 力" },
      { "en": "situation", "ja": "状況 人の置かれた 立場" },
      { "en": "environment", "ja": "環境" },
      { "en": "skill", "ja": "技能 熟練" },
      { "en": "view", "ja": "についての 見解 に対する 特定の 見方 眺め" },
      { "en": "value", "ja": "価値 価格 評価 価値観" },
      { "en": "species", "ja": "生物の 種 種類" },
      { "en": "thought", "ja": "考え 思考" },
      { "en": "knowledge", "ja": "知識 知っていること 認識" },
      { "en": "memory", "ja": "記憶 力 の 思い出" },
      { "en": "practice", "ja": "実践 実行 社会の 慣習 練習" },
      { "en": "benefit", "ja": "利益 恩恵 給付金" },
      { "en": "theory", "ja": "学説 理論 原理 推測" },
      { "en": "issue", "ja": "問題 点 発行 物 発表" },
      { "en": "experiment", "ja": "を対象とする 実験" },
      { "en": "article", "ja": "記事 条項 品物" },
      { "en": "focus", "ja": "焦点 関心の的" },
      { "en": "subject", "ja": "話題 科目 主題 被験者" },
      { "en": "project", "ja": "計画 事業 研究計画" },
      { "en": "quality", "ja": "質 特質" },
      { "en": "term", "ja": "専門 用語 条件 間柄 学期" },
      { "en": "statement", "ja": "声明 主張 明細書" },
      { "en": "material", "ja": "材料 素材 資料 生地" },
      { "en": "evidence", "ja": "証拠" },
      { "en": "source", "ja": "の 源 根源 出所 情報源" },
      { "en": "community", "ja": "共同 社会 界 地域社会 地域住民" },
      { "en": "technology", "ja": "科学技術 応用技術" },
      { "en": "culture", "ja": "文化 教養 耕作 養殖 培養" },
      { "en": "appropriate", "ja": "に 適切な" },
      { "en": "likely", "ja": "ありそうな ありそうもない" },
      { "en": "possible", "ja": "可能な 可能性のある" },
      { "en": "individual", "ja": "個々の 個人の" },
      { "en": "common", "ja": "共通の 普通の 一般の" },
      { "en": "certain", "ja": "確信して 確かな ある 一定の" },
      { "en": "similar", "ja": "似ている 類似した 同様の" },
      { "en": "recent", "ja": "最近の" },
      { "en": "major", "ja": "主要な 大きい ほうの 長調の" },
      { "en": "patient", "ja": "忍耐強い 勤勉な" },
      { "en": "particular", "ja": "特定の 特別の について やかましい" },
      { "en": "physical", "ja": "身体の 物質的な 物理学の" },
      { "en": "various", "ja": "さまざまな いくつかの" },
      { "en": "available", "ja": "手に入る 利用できる 手が空いている" },
      { "en": "native", "ja": "出生地の 原産の 生得の" },
      { "en": "political", "ja": "政治 上 の" },
      { "en": "due", "ja": "予定された 支払 期日で しかるべき" },
      { "en": "blank", "ja": "空白の 無表情な がらんとした" },
      { "en": "ancient", "ja": "古代の 昔からの" },
      { "en": "correct", "ja": "正しい 適切な" },
      { "en": "despite", "ja": "にもかかわらず" }
    ]
  },
  {
    "id": "audio_2",
    "name": "音声用セット 2 (101 - 200)",
    "words": [
      { "en": "refer", "ja": "言及する 関連する 参照する" },
      { "en": "recognize", "ja": "を識別できる を認める" },
      { "en": "solve", "ja": "を解く 解明する 困難など を解決する" },
      { "en": "occur", "ja": "起こる 心に浮かぶ 現れる" },
      { "en": "argue", "ja": "と主張する 議論する" },
      { "en": "express", "ja": "を表す 述べる" },
      { "en": "suppose", "ja": "と思う と仮定する" },
      { "en": "determine", "ja": "を決定する を正確に知る" },
      { "en": "prove", "ja": "を証明する 判明する わかる" },
      { "en": "apply", "ja": "を適用 応用 する 申し込む に 適用される" },
      { "en": "communicate", "ja": "と 情報交換をする を伝達する" },
      { "en": "contain", "ja": "を含む を収容する 感情など を抑える" },
      { "en": "regard", "ja": "を見なす を見る を評価する" },
      { "en": "range", "ja": "範囲 射程距離 同類の 組" },
      { "en": "access", "ja": "利用 入手 接近 の機会 方法 権利" },
      { "en": "current", "ja": "現在の 現代の 通用している" },
      { "en": "specific", "ja": "特定の 明確な 具体的な に 特有の" },
      { "en": "novel", "ja": "斬新な 目新しい" },
      { "en": "chemical", "ja": "化学の 化学的な" },
      { "en": "eventually", "ja": "結局 は" },
      { "en": "notice", "ja": "に気づく" },
      { "en": "approach", "ja": "に近づく に取り組む" },
      { "en": "wonder", "ja": "かなと思う に 驚く" },
      { "en": "imagine", "ja": "を 想像する を 推測する" },
      { "en": "claim", "ja": "と主張する を 自分のものとして 要求する" },
      { "en": "draw", "ja": "を引き出す を引く を描く 近づく" },
      { "en": "waste", "ja": "を浪費する 無駄にする" },
      { "en": "advance", "ja": "を進歩させる を進める 進歩する 進む" },
      { "en": "spread", "ja": "を広める 広がる" },
      { "en": "prepare", "ja": "を準備する を調理する のために 準備をする" },
      { "en": "gain", "ja": "を獲得する を 増す" },
      { "en": "achieve", "ja": "を達成する を成し遂げる" },
      { "en": "establish", "ja": "を確立する を設立する" },
      { "en": "supply", "ja": "を供給する" },
      { "en": "perform", "ja": "を 行う を 演じる を 演奏する" },
      { "en": "prefer", "ja": "のほうを好む" },
      { "en": "treat", "ja": "を扱う を治療する" },
      { "en": "mention", "ja": "に言及する と言う" },
      { "en": "contact", "ja": "と連絡を取る 接触する" },
      { "en": "respect", "ja": "を尊敬する を尊重する" },
      { "en": "search", "ja": "捜す を捜索する を詳しく調べる" },
      { "en": "connect", "ja": "をつなぐ を関連づける" },
      { "en": "decline", "ja": "減少する 衰退する を断る" },
      { "en": "prevent", "ja": "を妨げる を防ぐ" },
      { "en": "suffer", "ja": "苦しむ 患う 苦痛など を経験する" },
      { "en": "survive", "ja": "を切り抜けて生き残る より長生きする 生き延びる" },
      { "en": "publish", "ja": "を出版する を公表する" },
      { "en": "opportunity", "ja": "機会" },
      { "en": "task", "ja": "課せられた 仕事 作業 課題 タスク" },
      { "en": "industry", "ja": "産業 勤勉" },
      { "en": "medium", "ja": "情報伝達の 媒体 手段" },
      { "en": "economy", "ja": "経済 状態 経済圏 節約" },
      { "en": "policy", "ja": "政策 方針 個人の 主義" },
      { "en": "account", "ja": "説明 勘定 口座" },
      { "en": "trade", "ja": "貿易 商売 取引" },
      { "en": "model", "ja": "模範 モデル 模型 型" },
      { "en": "figure", "ja": "数字 姿 人物 図表" },
      { "en": "cell", "ja": "細胞 独房 電池" },
      { "en": "image", "ja": "印象 イメージ 画像 像" },
      { "en": "emotion", "ja": "感情 情動 感動" },
      { "en": "stress", "ja": "ストレス 圧力 強調" },
      { "en": "decade", "ja": "年間" },
      { "en": "character", "ja": "性格 個性 特徴 登場人物 文字" },
      { "en": "advantage", "ja": "利点 優勢 有利" },
      { "en": "phrase", "ja": "句 成句 言葉遣い" },
      { "en": "damage", "ja": "損害 損傷 損害賠償金" },
      { "en": "impact", "ja": "影響 激しい 衝突 衝撃 力" },
      { "en": "method", "ja": "方法 体系 秩序" },
      { "en": "resource", "ja": "通例 資源 通例 資金 才覚" },
      { "en": "region", "ja": "地域 領域 部位" },
      { "en": "medicine", "ja": "薬 医学" },
      { "en": "detail", "ja": "詳細 な情報 細部" },
      { "en": "feature", "ja": "特徴 通例 顔つき 特集記事 番組" },
      { "en": "function", "ja": "機能 関数" },
      { "en": "item", "ja": "品目 項目 同種の中の 個 短い 記事" },
      { "en": "income", "ja": "収入 所得" },
      { "en": "attitude", "ja": "態度 考え方 心構え" },
      { "en": "site", "ja": "用地 場所 跡地 ウェブ サイト" },
      { "en": "aspect", "ja": "物事の 側面 観点 様相" },
      { "en": "structure", "ja": "構造 体系 構造物" },
      { "en": "habit", "ja": "習慣 癖" },
      { "en": "link", "ja": "関連 つながり 地点を結ぶ 交通手段 リンク" },
      { "en": "instance", "ja": "具体的な 例 実例 特定の 場合" },
      { "en": "positive", "ja": "肯定的な 積極的な 確信して 検査結果が 陽性の" },
      { "en": "negative", "ja": "否定的な 消極的な 検査結果が 陰性の" },
      { "en": "complex", "ja": "複雑な 複合 体 の" },
      { "en": "mental", "ja": "精神の 知能の 頭の中で行う" },
      { "en": "significant", "ja": "重要な 重大な 意義深い" },
      { "en": "essential", "ja": "に 必要不可欠な 本質的な" },
      { "en": "official", "ja": "公用の 公式の 役所の" },
      { "en": "financial", "ja": "財政 上 の 財界の" },
      { "en": "academic", "ja": "学問の 大学の" },
      { "en": "aware", "ja": "気づいて 知って" },
      { "en": "worth", "ja": "する に値する の価値がある" },
      { "en": "potential", "ja": "潜在的な 可能性を秘めた" },
      { "en": "active", "ja": "積極的な 活動的な 効力のある" },
      { "en": "digital", "ja": "デジタル方式の デジタル 数字 表示の" },
      { "en": "mobile", "ja": "可動 移動 式の 流動性のある" },
      { "en": "plastic", "ja": "柔軟な プラスチックの ビニールの" },
      { "en": "necessary", "ja": "必要な" }
    ]
  },
  {
    "id": "audio_3",
    "name": "音声用セット 3 (201 - 300)",
    "words": [
      { "en": "observe", "ja": "に気づく を観察する を遵守する" },
      { "en": "reveal", "ja": "を明らかにする を見せる" },
      { "en": "pain", "ja": "苦痛 痛み 苦悩 骨折り" },
      { "en": "consequence", "ja": "通例 結果 重大性" },
      { "en": "ordinary", "ja": "一般の 普通の 並の" },
      { "en": "indicate", "ja": "を指し示す を述べる" },
      { "en": "associate", "ja": "を結び付けて考える と 交際する" },
      { "en": "attempt", "ja": "を試みる 企てる" },
      { "en": "unite", "ja": "を団結させる を 結合する 団結する" },
      { "en": "estimate", "ja": "と推定する を見積もる を評価する" },
      { "en": "match", "ja": "と 合う に匹敵する 一致する" },
      { "en": "display", "ja": "を示す を発揮する を展示 陳列 する" },
      { "en": "remove", "ja": "を取り除く を解雇する" },
      { "en": "wind", "ja": "ねじなど を巻く 道などが 曲がりくねる 巻きつく" },
      { "en": "assume", "ja": "を当然のことと思う と仮定する 権力など を手に入れる 責任など を引き受ける" },
      { "en": "desire", "ja": "を強く望む" },
      { "en": "charge", "ja": "料金 世話 管理 告発" },
      { "en": "colleague", "ja": "職場の 同僚" },
      { "en": "section", "ja": "部門 部分 地区 欄" },
      { "en": "conflict", "ja": "争い 論争 不一致" },
      { "en": "strategy", "ja": "戦略" },
      { "en": "basis", "ja": "基礎 根拠 基準" },
      { "en": "aim", "ja": "目的 目標 狙い" },
      { "en": "ancestor", "ja": "祖先 子孫 原型" },
      { "en": "track", "ja": "跡 軌道 米 鉄道の 番線 走路" },
      { "en": "revolution", "ja": "革命 回転 天体の 公転 自転" },
      { "en": "cognitive", "ja": "認知の" },
      { "en": "entire", "ja": "全体の 全部の 完全な" },
      { "en": "familiar", "ja": "精通している よく知られている" },
      { "en": "previous", "ja": "以前の 前の" },
      { "en": "urban", "ja": "都市の 都会的な" },
      { "en": "identify", "ja": "を特定する を と 同一視する" },
      { "en": "represent", "ja": "を表す を代表する に相当する" },
      { "en": "manage", "ja": "をなんとか成し遂げる を管理する" },
      { "en": "attend", "ja": "に出席する を 世話する に 対処 対応 する" },
      { "en": "maintain", "ja": "を維持する と主張する を養う" },
      { "en": "survey", "ja": "を調査する をじろじろ見る を概観する" },
      { "en": "replace", "ja": "に取って代わる を取り替える" },
      { "en": "sort", "ja": "を に 分類する を から えり分ける" },
      { "en": "conduct", "ja": "調査 実験など を実施する を導く" },
      { "en": "promote", "ja": "を促進する 通例受身形で 昇進する" },
      { "en": "earn", "ja": "を稼ぐ を得る をもたらす" },
      { "en": "feed", "ja": "に食べ物 乳 を与える に を 供給 補給 する 餌を食べる" },
      { "en": "seek", "ja": "を追い求める 助けなど を要請する" },
      { "en": "reflect", "ja": "を反映する を 反射する を 熟考する" },
      { "en": "attract", "ja": "を引きつける" },
      { "en": "decrease", "ja": "減少する を減らす" },
      { "en": "ignore", "ja": "を無視する" },
      { "en": "define", "ja": "を定義する を明確にする" },
      { "en": "adapt", "ja": "適応する を に 適合させる" },
      { "en": "contribute", "ja": "貢献する 一因となる を 寄付する を 寄稿する" },
      { "en": "exchange", "ja": "を 交換する 両替する" },
      { "en": "respond", "ja": "反応する 答える" },
      { "en": "hide", "ja": "を隠す 隠れる" },
      { "en": "doubt", "ja": "ではないと思う を疑う" },
      { "en": "relax", "ja": "くつろぐ 緩む をくつろがせる を緩める" },
      { "en": "satisfy", "ja": "を満足させる 条件など を満たす" },
      { "en": "succeed", "ja": "に 成功する を 継承する" },
      { "en": "concept", "ja": "概念 考え 商品 販売の コンセプト" },
      { "en": "fashion", "ja": "流行 ファッション 方法 流儀" },
      { "en": "device", "ja": "装置 機器 方策 デバイス" },
      { "en": "contrast", "ja": "との 対照" },
      { "en": "bill", "ja": "請求書 英 勘定書 米 法案" },
      { "en": "content", "ja": "内容 中身 コンテンツ" },
      { "en": "audience", "ja": "集合的に 聴衆 観客 視聴者" },
      { "en": "surface", "ja": "表面 外見" },
      { "en": "crop", "ja": "しばしば 作物 収穫高" },
      { "en": "topic", "ja": "話題 トピック 主題" },
      { "en": "technique", "ja": "技術 技巧 手法" },
      { "en": "status", "ja": "地位 状態" },
      { "en": "option", "ja": "選択 の自由 選択肢" },
      { "en": "reward", "ja": "報酬 報い" },
      { "en": "race", "ja": "人種 民族 競争" },
      { "en": "crime", "ja": "罪 犯罪 違法行為" },
      { "en": "struggle", "ja": "闘い 懸命の努力" },
      { "en": "context", "ja": "状況 背景 文脈" },
      { "en": "debate", "ja": "討論 論争 討論会" },
      { "en": "fuel", "ja": "燃料 勢いを増加させるもの" },
      { "en": "pollution", "ja": "汚染 公害" },
      { "en": "trend", "ja": "への 傾向 流行" },
      { "en": "balance", "ja": "均衡 バランス 体の 平衡 残高" },
      { "en": "traffic", "ja": "交通 通行 交通 輸送 量 不正 取引" },
      { "en": "gene", "ja": "遺伝子" },
      { "en": "progress", "ja": "進歩 前進" },
      { "en": "ideal", "ja": "理想的な 観念的な" },
      { "en": "efficient", "ja": "効率的な 有能な" },
      { "en": "universal", "ja": "普遍的な 宇宙の 万能の" },
      { "en": "vast", "ja": "莫大な 広大な" },
      { "en": "extra", "ja": "追加の 余分の 別勘定の" },
      { "en": "obvious", "ja": "明らかな" },
      { "en": "moral", "ja": "道徳 上 の 倫理的な 道徳的な" },
      { "en": "equal", "ja": "に 等しい 匹敵する 平等な" },
      { "en": "FALSE", "ja": "間違った 虚偽の 偽の" },
      { "en": "rare", "ja": "まれな 珍しい 希少な" },
      { "en": "legal", "ja": "法律の 合法の 違法の" },
      { "en": "independent", "ja": "から 独立した" },
      { "en": "extreme", "ja": "極端な 極度の 過激な" },
      { "en": "actual", "ja": "実際の 現実の" },
      { "en": "willing", "ja": "いとわない かまわないと思う" },
      { "en": "whereas", "ja": "するのに 対し する一方" }
    ]
  },
  {
    "id": "audio_4",
    "name": "音声用セット 4 (301 - 400)",
    "words": [
      { "en": "trust", "ja": "を信頼する を 信頼して 託す" },
      { "en": "emerge", "ja": "現れる 明らかになる 台頭する" },
      { "en": "vary", "ja": "さまざまである 変わる を変える" },
      { "en": "divide", "ja": "を分ける 分かれる" },
      { "en": "engage", "ja": "を従事させる を として 雇う に 従事する" },
      { "en": "shift", "ja": "を変える 移す 変わる 移動する" },
      { "en": "acquire", "ja": "を得る を習得する" },
      { "en": "expand", "ja": "を 拡大する を 詳説する" },
      { "en": "consume", "ja": "を消費する を食べる 飲む" },
      { "en": "evolve", "ja": "徐々に 発展する 進化する" },
      { "en": "surround", "ja": "を取り巻く にまつわる" },
      { "en": "combine", "ja": "を と 結び付ける と 結び付く" },
      { "en": "extend", "ja": "を伸 延 ばす 伸びる 及ぶ" },
      { "en": "appreciate", "ja": "を正当に評価する を鑑賞する を感謝する" },
      { "en": "element", "ja": "要素 成分 元素 で 少しの" },
      { "en": "phenomenon", "ja": "現象" },
      { "en": "manner", "ja": "作法 方法 物腰" },
      { "en": "resident", "ja": "居住者 滞在者" },
      { "en": "authority", "ja": "通例 関係 当局 権威 権限" },
      { "en": "fund", "ja": "しばしば 基金 資金" },
      { "en": "analysis", "ja": "分析 結果" },
      { "en": "perspective", "ja": "観点 見方 大局観 遠近法" },
      { "en": "crisis", "ja": "危機" },
      { "en": "psychology", "ja": "心理学 心理 状態" },
      { "en": "soil", "ja": "土地 土壌 悪事などの 温床" },
      { "en": "agriculture", "ja": "農業 農学 畜産" },
      { "en": "capable", "ja": "能力がある 有能な" },
      { "en": "fundamental", "ja": "基本的な 必須の" },
      { "en": "firm", "ja": "確固たる 堅固な 安定した" },
      { "en": "constant", "ja": "絶え間ない 一定の" },
      { "en": "convenient", "ja": "便利な 都合のいい" },
      { "en": "mass", "ja": "大規模な 大量の 大衆 向け の" },
      { "en": "overseas", "ja": "海外へ に で" },
      { "en": "nevertheless", "ja": "それにもかかわらず" },
      { "en": "predict", "ja": "を予言 予測 する" },
      { "en": "examine", "ja": "を調べる を診察する を尋問する" },
      { "en": "release", "ja": "を放出する を解放する を発表する" },
      { "en": "enable", "ja": "人 が できるようにする を可能にする" },
      { "en": "adopt", "ja": "を採用する 態度など をとる を養子にする" },
      { "en": "confuse", "ja": "を混同する を当惑させる" },
      { "en": "convince", "ja": "を納得 確信 させる" },
      { "en": "preserve", "ja": "を保存する を保持する を保護する" },
      { "en": "organize", "ja": "を準備する を組織する" },
      { "en": "warn", "ja": "人 に を 警告 注意 する" },
      { "en": "address", "ja": "問題など に対処する に演説する 手紙など を 宛てに 出す" },
      { "en": "operate", "ja": "を操作する 機能する 手術する" },
      { "en": "participate", "ja": "参加する" },
      { "en": "flow", "ja": "流れる から 生じる" },
      { "en": "bore", "ja": "人 を退屈させる うんざりさせる" },
      { "en": "origin", "ja": "起源 源" },
      { "en": "personality", "ja": "個性 性格" },
      { "en": "capacity", "ja": "最大 容量 収容能力 潜在 能力" },
      { "en": "profit", "ja": "利益 収益 率 得" },
      { "en": "circumstance", "ja": "通例 状況 事情 境遇" },
      { "en": "threat", "ja": "脅威 悪い 兆し 脅迫" },
      { "en": "wealth", "ja": "富 資源 富裕" },
      { "en": "institution", "ja": "機関 協会 施設 制度" },
      { "en": "sight", "ja": "光景 名所 見 え ること 視野 視力" },
      { "en": "version", "ja": "本 製品などの 版 解釈" },
      { "en": "intelligent", "ja": "聡明な 知能を有する" },
      { "en": "conscious", "ja": "意識して 気づいて" },
      { "en": "accurate", "ja": "正確な 精密な" },
      { "en": "overall", "ja": "総合的な 全体的な" },
      { "en": "nuclear", "ja": "核の 原子力の" },
      { "en": "biological", "ja": "生物学 上 の" },
      { "en": "severe", "ja": "人 規律 事態 天気などが 厳しい 猛烈な" },
      { "en": "visual", "ja": "視覚の 目に見える" },
      { "en": "enormous", "ja": "莫大な 巨大な" },
      { "en": "typical", "ja": "典型的な に 特有の" },
      { "en": "stick", "ja": "を動けなくする を突き刺す に くっつく" },
      { "en": "judge", "ja": "を 判断する に判決を下す" },
      { "en": "rely", "ja": "頼る" },
      { "en": "refuse", "ja": "を拒む を断る 拒絶する" },
      { "en": "strike", "ja": "の心を打つ を襲う を打つ に ぶつかる" },
      { "en": "repeat", "ja": "を 繰り返す を復唱する" },
      { "en": "select", "ja": "を選ぶ えり抜く" },
      { "en": "recall", "ja": "を思い出す を呼び戻す" },
      { "en": "destroy", "ja": "を破壊する 人 を破滅させる" },
      { "en": "complain", "ja": "と 不平 苦情 を言う 訴える" },
      { "en": "host", "ja": "を主催する のホスト役を務める" },
      { "en": "target", "ja": "到達 攻撃 目標 的" },
      { "en": "principle", "ja": "原則 原理 主義 信条" },
      { "en": "atmosphere", "ja": "大気 雰囲気" },
      { "en": "vote", "ja": "投票 投票結果 選挙権" },
      { "en": "campaign", "ja": "運動 軍事行動" },
      { "en": "web", "ja": "ウェブ クモの 巣" },
      { "en": "symbol", "ja": "象徴 シンボル 記号 標章" },
      { "en": "disaster", "ja": "災害 惨事" },
      { "en": "lecture", "ja": "講義 講演 説教" },
      { "en": "gender", "ja": "社会的 文化的 性 性別" },
      { "en": "custom", "ja": "社会的な 慣習 税関 関税" },
      { "en": "court", "ja": "裁判所 法廷 裁判 宮廷 中庭" },
      { "en": "desert", "ja": "砂漠 不毛の地" },
      { "en": "fossil", "ja": "化石 時代遅れの人 物" },
      { "en": "document", "ja": "公 文書 書類 記録 資料" },
      { "en": "vocabulary", "ja": "語彙" },
      { "en": "artificial", "ja": "人工の 自然の 不自然な" },
      { "en": "rural", "ja": "田舎の 田園の" },
      { "en": "military", "ja": "軍の 軍事 用 の" },
      { "en": "domestic", "ja": "家庭の 国内の 動物が 飼いならされた" }
    ]
  },
  {
    "id": "audio_5",
    "name": "音声用セット 5 (401 - 500)",
    "words": [
      { "en": "tear", "ja": "を引き裂く 裂ける" },
      { "en": "perceive", "ja": "に気づく を知覚する を理解する" },
      { "en": "imply", "ja": "を暗に意味する を必然的に伴う" },
      { "en": "handle", "ja": "を処理する 扱う を論じる を商う" },
      { "en": "praise", "ja": "を のことで 賞賛する 賛美する" },
      { "en": "insist", "ja": "を 強く主張する 要求する" },
      { "en": "compete", "ja": "競う 通例否定文で に 匹敵する" },
      { "en": "deny", "ja": "を否定する を拒む" },
      { "en": "reject", "ja": "を拒否する" },
      { "en": "expose", "ja": "をさらす を暴露する を露出する" },
      { "en": "favor", "ja": "に賛成する を好む をひいきする" },
      { "en": "inspire", "ja": "人 を奮起させる を喚起する" },
      { "en": "religion", "ja": "宗教 信条 信仰 心" },
      { "en": "presence", "ja": "存在 出席 面前" },
      { "en": "harm", "ja": "害 損害" },
      { "en": "notion", "ja": "概念 観念 見解 意向" },
      { "en": "trait", "ja": "特性" },
      { "en": "victim", "ja": "犠牲 者 被害者" },
      { "en": "occasion", "ja": "場合 時 行事 機会" },
      { "en": "facility", "ja": "施設 設備 機能 才能" },
      { "en": "stock", "ja": "在庫品 蓄え 株" },
      { "en": "conference", "ja": "会議 協議" },
      { "en": "humanity", "ja": "人類 人間性 人情 人文科学" },
      { "en": "dialect", "ja": "方言" },
      { "en": "proportion", "ja": "割合 部分 釣り合い" },
      { "en": "lawyer", "ja": "弁護士" },
      { "en": "organ", "ja": "器官 臓器 組織 パイプ オルガン" },
      { "en": "norm", "ja": "規範 標準" },
      { "en": "numerous", "ja": "非常に数の多い" },
      { "en": "sufficient", "ja": "に するのに 十分な" },
      { "en": "strict", "ja": "規則などが 厳しい 厳格な" },
      { "en": "civil", "ja": "市民の 民間の 民事の 刑事の" },
      { "en": "odd", "ja": "奇妙な 奇数の" },
      { "en": "unknown", "ja": "不明の に 知られていない 無名の" },
      { "en": "virtual", "ja": "仮想の 事実上の" },
      { "en": "crucial", "ja": "重要な" },
      { "en": "educate", "ja": "を教育する に教える 能力など を養う" },
      { "en": "purchase", "ja": "を購入する" },
      { "en": "admit", "ja": "を しぶしぶ 認める に への 入場 入学など を認める" },
      { "en": "generate", "ja": "を生み出す 電気など を発生させる" },
      { "en": "explore", "ja": "を 調査 探究 する を 探検 探査 する" },
      { "en": "afford", "ja": "を持つ する 余裕がある を与える" },
      { "en": "conclude", "ja": "と結論づける を締めくくる を締結する" },
      { "en": "encounter", "ja": "に遭遇する に 思いがけず 出会う" },
      { "en": "remind", "ja": "に思い出させる" },
      { "en": "aid", "ja": "を援助する 助ける" },
      { "en": "deliver", "ja": "を配達する 演説 講義 をする 子を産む" },
      { "en": "appeal", "ja": "訴える 抗議する 上級審に 上訴する" },
      { "en": "rank", "ja": "を位置づける 評価する ある地位に 位置する" },
      { "en": "intend", "ja": "を意図する" },
      { "en": "breathe", "ja": "呼吸する を吸う" },
      { "en": "repair", "ja": "を修理する を修復する" },
      { "en": "consist", "ja": "から 成る に ある" },
      { "en": "instruction", "ja": "通例 指示 製品の 使用書" },
      { "en": "neighborhood", "ja": "地域 近所" },
      { "en": "instrument", "ja": "器具 楽器" },
      { "en": "category", "ja": "部類 区分 範疇" },
      { "en": "capital", "ja": "資本 首都 大文字" },
      { "en": "outcome", "ja": "結果 成果" },
      { "en": "review", "ja": "書物などの 論評 再調査 米 復習" },
      { "en": "diversity", "ja": "多様性 相違点" },
      { "en": "tip", "ja": "助言 秘訣 チップ 先端" },
      { "en": "stuff", "ja": "漠然と 物 素材 素質" },
      { "en": "comfort", "ja": "快適さ 慰め" },
      { "en": "philosophy", "ja": "哲学 原理 人生観" },
      { "en": "mammal", "ja": "哺乳動物" },
      { "en": "quantity", "ja": "量 分量" },
      { "en": "tribe", "ja": "部族 仲間" },
      { "en": "code", "ja": "規範 暗号 法典" },
      { "en": "substance", "ja": "物質 実体 趣旨" },
      { "en": "multiple", "ja": "多様な 種々雑多な" },
      { "en": "widespread", "ja": "広範囲にわたる 広く普及した" },
      { "en": "proper", "ja": "適切な 正式の 名詞の後ろで 主要な に 固有の" },
      { "en": "linguistic", "ja": "言語の 言語学の" },
      { "en": "annual", "ja": "年 回の 例年の 年間の" },
      { "en": "contemporary", "ja": "現代の 同時代の 同年輩の" },
      { "en": "contrary", "ja": "と 反対の" },
      { "en": "sensitive", "ja": "敏感な 神経質な 微妙な" },
      { "en": "violent", "ja": "人 気質などが 激しい 暴力的な" },
      { "en": "regardless", "ja": "に かまわない 無頓着な" },
      { "en": "somewhat", "ja": "いくぶん 多少" },
      { "en": "demonstrate", "ja": "を論証 証明 する デモをする" },
      { "en": "behave", "ja": "振る舞う 作動する" },
      { "en": "recommend", "ja": "を勧める" },
      { "en": "amaze", "ja": "をびっくりさせる" },
      { "en": "settle", "ja": "を解決する に 移り住む を落ち着かせる" },
      { "en": "advertise", "ja": "を宣伝する を求める 広告を出す" },
      { "en": "locate", "ja": "受身形で 位置する の位置を探し当てる" },
      { "en": "bite", "ja": "を かむ に かみつく を 刺す" },
      { "en": "distinguish", "ja": "を区別する" },
      { "en": "propose", "ja": "を提案する をもくろむ 結婚を申し込む" },
      { "en": "spell", "ja": "語 をつづる という語になる" },
      { "en": "comment", "ja": "意見 コメント 批判" },
      { "en": "laboratory", "ja": "実験室 研究室" },
      { "en": "confidence", "ja": "自信 信頼 秘密" },
      { "en": "landscape", "ja": "風景 領域 状況" },
      { "en": "trial", "ja": "試み 品質 性能などの 試験 裁判 試用期間" },
      { "en": "narrow", "ja": "狭い 細い 限られた" },
      { "en": "superior", "ja": "よりすぐれた" },
      { "en": "immediate", "ja": "即座の 当面の すぐそばの 直接の" }
    ]
  },
  {
    "id": "audio_6",
    "name": "音声用セット 6 (501 - 600)",
    "words": [
      { "en": "request", "ja": "に するように 頼む を要請する" },
      { "en": "criticize", "ja": "を批判する を批評する" },
      { "en": "overcome", "ja": "を克服する" },
      { "en": "obtain", "ja": "を得る" },
      { "en": "announce", "ja": "を発表 公表 する 知らせる 物事が を告げる" },
      { "en": "differ", "ja": "異なる" },
      { "en": "hate", "ja": "をひどく嫌う を残念に思う" },
      { "en": "credit", "ja": "功績など を に 帰する を信じる" },
      { "en": "alter", "ja": "を変える 変わる" },
      { "en": "transport", "ja": "を輸送する を運ぶ" },
      { "en": "rush", "ja": "急いで行く 性急に行動する をせき立てる" },
      { "en": "blame", "ja": "を責める の責任を負わせる" },
      { "en": "fascinate", "ja": "を魅了する" },
      { "en": "expense", "ja": "経費 費用 犠牲" },
      { "en": "alarm", "ja": "不安 恐れ 警報装置" },
      { "en": "democracy", "ja": "民主主義 民主政治 民主国家" },
      { "en": "fellow", "ja": "仲間 同僚 同級生 男" },
      { "en": "immigration", "ja": "他国からの 移民 移住 入国管理" },
      { "en": "barrier", "ja": "に対する 障壁 防壁" },
      { "en": "hypothesis", "ja": "仮説 憶測" },
      { "en": "client", "ja": "顧客 弁護士などの 依頼人" },
      { "en": "grain", "ja": "穀物 粒 きめ" },
      { "en": "ingredient", "ja": "材料 成分 成功の 要因" },
      { "en": "contract", "ja": "契約 書 協定" },
      { "en": "prime", "ja": "主要な 最も重要な 最適な 極上の" },
      { "en": "distinct", "ja": "明らかに異なる 明瞭な" },
      { "en": "conventional", "ja": "従来の 月並みな" },
      { "en": "abstract", "ja": "抽象的な" },
      { "en": "stable", "ja": "安定した 不安定な 動じない" },
      { "en": "aggressive", "ja": "攻撃的な 意欲的な" },
      { "en": "visible", "ja": "目に 見える 見えない 明白な" },
      { "en": "unexpected", "ja": "思いがけない 不意の" },
      { "en": "alien", "ja": "にとって 異質の 外国の 宇宙人の" },
      { "en": "latter", "ja": "後者の 前者の 後半の" },
      { "en": "translate", "ja": "を翻訳する を に 変える" },
      { "en": "concentrate", "ja": "を 集中する" },
      { "en": "grant", "ja": "人 に 許可 権利など を与える を認める" },
      { "en": "oppose", "ja": "に反対する を対抗 対比 させる" },
      { "en": "employ", "ja": "を雇う を使う" },
      { "en": "transform", "ja": "を変える 変わる" },
      { "en": "construct", "ja": "を建設する を構成する" },
      { "en": "arise", "ja": "生じる" },
      { "en": "beat", "ja": "を打ち負かす を 打つ たたく" },
      { "en": "regret", "ja": "を後悔する" },
      { "en": "absorb", "ja": "を吸収する を併合する を夢中にさせる" },
      { "en": "cure", "ja": "を治す を取り除く 病気が 治る" },
      { "en": "hang", "ja": "を掛ける を絞首刑にする 垂れ 下が る" },
      { "en": "recover", "ja": "回復する を取り戻す" },
      { "en": "celebrate", "ja": "を祝う を挙行する" },
      { "en": "manufacture", "ja": "を製造する をでっち上げる" },
      { "en": "interact", "ja": "影響し合う 相互に作用する" },
      { "en": "arrange", "ja": "の段取りをつける を手配する を配置する" },
      { "en": "adjust", "ja": "を調整する を適合させる 順応する" },
      { "en": "confirm", "ja": "を確認する を裏づける" },
      { "en": "budget", "ja": "予算 経費" },
      { "en": "fee", "ja": "料金 謝礼" },
      { "en": "debt", "ja": "借金 負債 恩義" },
      { "en": "loan", "ja": "貸付金 融資 貸すこと" },
      { "en": "emergency", "ja": "緊急 事態" },
      { "en": "corporation", "ja": "大 企業 法人" },
      { "en": "route", "ja": "道 筋 路線 ルート の 手段" },
      { "en": "weapon", "ja": "兵器 武器" },
      { "en": "disadvantage", "ja": "不利 な点 障害 信用などの 損失" },
      { "en": "mood", "ja": "気分 機嫌 雰囲気" },
      { "en": "discipline", "ja": "規律 しつけ 訓練 懲戒 学問分野" },
      { "en": "colony", "ja": "植民地 集団居住地 動植物の コロニー" },
      { "en": "treasure", "ja": "宝物 財宝 財産" },
      { "en": "welfare", "ja": "福祉 幸福" },
      { "en": "curious", "ja": "好奇心の強い 奇妙な" },
      { "en": "dramatic", "ja": "劇的な 演劇の" },
      { "en": "anxious", "ja": "心配して 切望して" },
      { "en": "vital", "ja": "必要不可欠な 活気のある 生命にかかわる" },
      { "en": "brief", "ja": "簡潔な 短い" },
      { "en": "ethnic", "ja": "民族の 人種の 民族特有の" },
      { "en": "initial", "ja": "初めの" },
      { "en": "exact", "ja": "正確な まさにその" },
      { "en": "precise", "ja": "正確な 精密な まさにその" },
      { "en": "interpret", "ja": "を解釈する を 通訳する" },
      { "en": "ban", "ja": "を 法的に 禁止する を締め出す" },
      { "en": "innovation", "ja": "革新 新機軸" },
      { "en": "minister", "ja": "大臣 プロテスタント系の 聖職者" },
      { "en": "stereotype", "ja": "固定観念 決まり文句" },
      { "en": "depression", "ja": "憂うつ うつ病 不況 低気圧" },
      { "en": "motion", "ja": "動き 動作 運動 動議" },
      { "en": "myth", "ja": "作り話 神話" },
      { "en": "inform", "ja": "に知らせる 情報を提供する" },
      { "en": "ensure", "ja": "を確実にする を守る" },
      { "en": "freeze", "ja": "凍る を凍らせる 計画 資金など を凍結する" },
      { "en": "emphasize", "ja": "を強調する を重視する" },
      { "en": "disappoint", "ja": "を失望させる 希望など をくじく" },
      { "en": "insight", "ja": "見識 理解 力 洞察力" },
      { "en": "duty", "ja": "義務 しばしば 職務 関税" },
      { "en": "candidate", "ja": "の 候補 者 志願者" },
      { "en": "disorder", "ja": "障害 心身の 不調 混乱" },
      { "en": "routine", "ja": "決まり切った仕事 いつもの手順" },
      { "en": "physician", "ja": "主に米 医師 内科医" },
      { "en": "statistics", "ja": "統計 統計学" },
      { "en": "minor", "ja": "重要でない 小さい" },
      { "en": "extraordinary", "ja": "並はずれた 異常な 驚くべき" },
      { "en": "flexible", "ja": "融通の利く 柔軟な" }
    ]
  },
  {
    "id": "audio_7",
    "name": "音声用セット 7 (601 - 700)",
    "words": [
      { "en": "enhance", "ja": "価値など を高める 増す" },
      { "en": "stare", "ja": "じっと見る を見つめる" },
      { "en": "quit", "ja": "をやめる 場所 を去る" },
      { "en": "capture", "ja": "をとらえる をとりこにする" },
      { "en": "transfer", "ja": "を移す を伝える 移る 乗り換える" },
      { "en": "persuade", "ja": "を説得する に確信させる" },
      { "en": "breed", "ja": "を繁殖させる 育てる 繁殖する" },
      { "en": "reserve", "ja": "を予約する を取っておく 判断など を保留する" },
      { "en": "permit", "ja": "を許可する" },
      { "en": "investigate", "ja": "を調査する を究明する を 調査する" },
      { "en": "eliminate", "ja": "を取り除く" },
      { "en": "ease", "ja": "を軽減する 和らぐ 緩む" },
      { "en": "symptom", "ja": "症状 兆候" },
      { "en": "exception", "ja": "の 例外" },
      { "en": "virus", "ja": "ウイルス 感染症の 病原体" },
      { "en": "surgery", "ja": "外科 手術 外科 外科医学" },
      { "en": "insurance", "ja": "保険 保険料 保険金" },
      { "en": "boundary", "ja": "境界 線 通例 限界" },
      { "en": "district", "ja": "地区 行政区" },
      { "en": "harvest", "ja": "収穫 物 収穫期 漁獲高" },
      { "en": "trick", "ja": "こつ 策略 いたずら 芸当" },
      { "en": "cooperation", "ja": "協力 共同" },
      { "en": "patent", "ja": "特許 権 特許品" },
      { "en": "reputation", "ja": "評判 名声" },
      { "en": "principal", "ja": "主要な 資本金の" },
      { "en": "rational", "ja": "理性的な 合理的な" },
      { "en": "frequent", "ja": "頻繁な" },
      { "en": "random", "ja": "無作為の 手当たり次第の" },
      { "en": "mere", "ja": "単なる ほんの" },
      { "en": "stimulate", "ja": "を刺激する" },
      { "en": "disagree", "ja": "不賛成である 意見が食い違う" },
      { "en": "abandon", "ja": "を捨てる を放棄する 断念する" },
      { "en": "rent", "ja": "を賃借りする を賃貸しする" },
      { "en": "trace", "ja": "足跡 起源など をたどる を捜し出す" },
      { "en": "advise", "ja": "に忠告 助言 する を 助言する" },
      { "en": "stretch", "ja": "を伸ばす を広げる 伸びる 及ぶ" },
      { "en": "crash", "ja": "衝突する 墜落する をぶつけて壊す" },
      { "en": "impress", "ja": "を感動させる に印象を与える" },
      { "en": "upset", "ja": "を動揺させる をだめにする" },
      { "en": "monitor", "ja": "を監視する を傍受する" },
      { "en": "launch", "ja": "を開始する を売り出す を発射する" },
      { "en": "therapy", "ja": "療法 心理療法" },
      { "en": "burden", "ja": "負担 重い 義務 積み荷" },
      { "en": "honor", "ja": "光栄 名誉 不名誉 敬意" },
      { "en": "habitat", "ja": "生息地 人の 居住地" },
      { "en": "trap", "ja": "わな 苦境" },
      { "en": "fault", "ja": "通例" },
      { "en": "ones", "ja": "責任 欠点 誤り" },
      { "en": "discount", "ja": "割引" },
      { "en": "bias", "ja": "偏見 傾向" },
      { "en": "dialogue", "ja": "対話 会話 意見の交換" },
      { "en": "verbal", "ja": "言葉の 口頭での 動詞の" },
      { "en": "permanent", "ja": "永続的な" },
      { "en": "rude", "ja": "無礼な 礼儀正しい 粗野な" },
      { "en": "tropical", "ja": "熱帯の" },
      { "en": "invest", "ja": "を 投資する に を 与える" },
      { "en": "import", "ja": "を輸入する を 輸出する を取り込む" },
      { "en": "tone", "ja": "口調 音色 雰囲気 色調" },
      { "en": "minimum", "ja": "最小限度" },
      { "en": "frame", "ja": "枠 額 縁 骨組み 体格" },
      { "en": "territory", "ja": "領土 活動の 領域 動物の テリトリー" },
      { "en": "internal", "ja": "内部の 国内の 内面的な" },
      { "en": "meaningful", "ja": "意味のある" },
      { "en": "commit", "ja": "または受身形で 献身する 罪など を犯す を投入する" },
      { "en": "pursue", "ja": "を追求する に従事する" },
      { "en": "react", "ja": "反応する 化学反応を起こす" },
      { "en": "bother", "ja": "を悩ます を 気にかける" },
      { "en": "illustrate", "ja": "を説明する に挿絵を入れる" },
      { "en": "convey", "ja": "を伝える を運ぶ 運搬する" },
      { "en": "attach", "ja": "を 取り 付ける を付与する" },
      { "en": "puzzle", "ja": "を当惑させる" },
      { "en": "disturb", "ja": "をかき乱す を妨害する を動揺させる" },
      { "en": "cope", "ja": "うまく処理する" },
      { "en": "suspect", "ja": "ではないかと思う 人 を疑う" },
      { "en": "frighten", "ja": "人 を怖がらせる" },
      { "en": "export", "ja": "を 輸出する を輸入する" },
      { "en": "calculate", "ja": "を計算する を予測する" },
      { "en": "sequence", "ja": "連続 一連 のもの" },
      { "en": "incident", "ja": "出来事 事件 紛争" },
      { "en": "witness", "ja": "目撃者 証人 証拠 証言" },
      { "en": "sum", "ja": "金 額 合計 要点" },
      { "en": "award", "ja": "の 賞 証書などの 授与" },
      { "en": "priority", "ja": "優先 事項" },
      { "en": "logic", "ja": "論理 道理 論理学" },
      { "en": "clue", "ja": "の 手がかり パズルの ヒント" },
      { "en": "bond", "ja": "絆 債券 束縛 接着剤" },
      { "en": "shelter", "ja": "避難 所 保護" },
      { "en": "conservation", "ja": "動植物などの 保護 保存" },
      { "en": "predator", "ja": "捕食動物 略奪者" },
      { "en": "component", "ja": "構成要素 部品" },
      { "en": "solid", "ja": "しっかりした 硬い 固体の" },
      { "en": "remote", "ja": "から 遠く離れた かけ離れた" },
      { "en": "sophisticated", "ja": "高性能の 精巧な 洗練された" },
      { "en": "equivalent", "ja": "等しい 相当する" },
      { "en": "relevant", "ja": "関係がある 適切な" },
      { "en": "absolute", "ja": "絶対的な 相対的な" },
      { "en": "intense", "ja": "強烈な 熱烈な" },
      { "en": "evil", "ja": "邪悪な 有害な" },
      { "en": "extinct", "ja": "絶滅した 廃止された" },
      { "en": "raw", "ja": "生の 未加工の" }
    ]
  },
  {
    "id": "audio_8",
    "name": "音声用セット 8 (701 - 800)",
    "words": [
      { "en": "forth", "ja": "前へ 先へ それ以降" },
      { "en": "possess", "ja": "を所有している の心をとらえる" },
      { "en": "dominate", "ja": "を支配する より 優勢である" },
      { "en": "embarrass", "ja": "に恥ずかしい思いをさせる" },
      { "en": "discourage", "ja": "人 にやる気をなくさせる を落胆させる" },
      { "en": "encourage", "ja": "" },
      { "en": "devote", "ja": "をささげる" },
      { "en": "urge", "ja": "に 強く 促す を強く主張する を駆り立てる" },
      { "en": "exhaust", "ja": "を疲れ果てさせる を使い尽くす 排気する" },
      { "en": "annoy", "ja": "を悩ます 受身形で 腹が立つ" },
      { "en": "endanger", "ja": "を危険にさらす" },
      { "en": "admire", "ja": "に のことで 敬服 感心 する" },
      { "en": "evaluate", "ja": "を評価する を査定する" },
      { "en": "secure", "ja": "を確保する を守る" },
      { "en": "specialize", "ja": "専門とする 英 を 専攻する 米" },
      { "en": "attribute", "ja": "結果など を に 帰する" },
      { "en": "reverse", "ja": "を逆転させる を反対にする" },
      { "en": "retire", "ja": "から 引退する 退職する 退く" },
      { "en": "neglect", "ja": "をおろそかにする 怠る を無視する" },
      { "en": "sustain", "ja": "を持続させる を支える" },
      { "en": "assign", "ja": "を割り当てる を に 配属する" },
      { "en": "mission", "ja": "使命 外交 使節団 布教" },
      { "en": "motor", "ja": "モーター 原動力" },
      { "en": "agent", "ja": "仲介者 代理人 薬剤" },
      { "en": "sacrifice", "ja": "犠牲 いけにえ" },
      { "en": "means", "ja": "単数 複数扱い 手段 複数扱い 資力 収入" },
      { "en": "league", "ja": "競技 連盟 同盟" },
      { "en": "guard", "ja": "警備員 警備隊 監視 警戒" },
      { "en": "opponent", "ja": "試合 論争などの 相手 反対者" },
      { "en": "prejudice", "ja": "に対する 偏見" },
      { "en": "sector", "ja": "社会 経済などの 部門 セクター 都市内の 地域" },
      { "en": "usage", "ja": "使 用法 語法 習慣" },
      { "en": "fortune", "ja": "財産 幸運 運命" },
      { "en": "correlation", "ja": "相互関係 相関 関係" },
      { "en": "primitive", "ja": "原始的な 未開の" },
      { "en": "subtle", "ja": "微妙な 気体などが 希薄な" },
      { "en": "plain", "ja": "明らかな 平易な 飾りのない 率直な" },
      { "en": "marine", "ja": "海の 船舶の" },
      { "en": "apparent", "ja": "明白な 一見 らしい" },
      { "en": "reluctant", "ja": "気が進まない 嫌がる" },
      { "en": "guilty", "ja": "罪悪感のある について 有罪の" },
      { "en": "pure", "ja": "純粋な 潔白な まったくの" },
      { "en": "eager", "ja": "を 熱望して 熱心な" },
      { "en": "adequate", "ja": "十分な 適切な 不適切な" },
      { "en": "via", "ja": "経由で の媒介で" },
      { "en": "guarantee", "ja": "を保証する" },
      { "en": "detect", "ja": "を感知する を見つけ出す に気づく" },
      { "en": "lend", "ja": "を貸す を借りる 人 に 助言 援助など を与える" },
      { "en": "restrict", "ja": "を制限する" },
      { "en": "isolate", "ja": "を孤立させる" },
      { "en": "accompany", "ja": "に同行する に付随する" },
      { "en": "acknowledge", "ja": "事実など を認める に謝意を表す" },
      { "en": "declare", "ja": "を宣言する を申告する" },
      { "en": "pretend", "ja": "の ふりをする" },
      { "en": "bury", "ja": "を埋める を埋葬する を隠す" },
      { "en": "resist", "ja": "に抵抗する 通例否定文で を我慢する" },
      { "en": "scare", "ja": "をおびえさせる を脅す" },
      { "en": "assist", "ja": "を 援助する を手伝う" },
      { "en": "resemble", "ja": "に似ている" },
      { "en": "collapse", "ja": "崩壊する 人が 倒れる を折り畳む" },
      { "en": "reform", "ja": "を改革する を改心させる" },
      { "en": "protest", "ja": "に 抗議する を主張する" },
      { "en": "owe", "ja": "に借りがある のおかげである" },
      { "en": "accomplish", "ja": "を成し遂げる" },
      { "en": "wisdom", "ja": "知恵 賢明さ 学識" },
      { "en": "literacy", "ja": "読み書きの能力 特定分野の 知識" },
      { "en": "heritage", "ja": "遺産" },
      { "en": "license", "ja": "免許 証 許可" },
      { "en": "elite", "ja": "通例" },
      { "en": "the", "ja": "集合的に エリート" },
      { "en": "layer", "ja": "層" },
      { "en": "protein", "ja": "たんぱく質" },
      { "en": "profession", "ja": "職業 専門職 同業者仲間" },
      { "en": "haven", "ja": "避難所 保護区 港" },
      { "en": "row", "ja": "列 建物が並ぶ 通り" },
      { "en": "session", "ja": "集まり 議会の 会期 開会中の 議会" },
      { "en": "contest", "ja": "コンテスト 競技 会 争い" },
      { "en": "glance", "ja": "を ちらっと見ること" },
      { "en": "divorce", "ja": "離婚 分離" },
      { "en": "tissue", "ja": "生物の 組織 ティッシュペーパー" },
      { "en": "liquid", "ja": "液体" },
      { "en": "inequality", "ja": "不平等 不公平な事柄" },
      { "en": "justice", "ja": "公正 正義 司法" },
      { "en": "guideline", "ja": "指針 ガイドライン 指導基準" },
      { "en": "platform", "ja": "プラットフォーム 演壇 舞台" },
      { "en": "channel", "ja": "チャンネル 伝達経路 海峡" },
      { "en": "glacier", "ja": "氷河" },
      { "en": "primate", "ja": "霊長目の動物" },
      { "en": "literary", "ja": "文学の 文語の 口語体の" },
      { "en": "classic", "ja": "第一級の 典型的な 定番の" },
      { "en": "slight", "ja": "わずかな 取るに足らない" },
      { "en": "federal", "ja": "連邦 政府 の" },
      { "en": "unfamiliar", "ja": "に 不慣れな に よく 知られていない" },
      { "en": "temporary", "ja": "一時的な" },
      { "en": "royal", "ja": "王の" },
      { "en": "incredible", "ja": "信じられない すばらしい" },
      { "en": "melt", "ja": "溶ける なごむ を溶かす" },
      { "en": "imitate", "ja": "をまねる を模造する" },
      { "en": "editor", "ja": "編集者 編集長" },
      { "en": "globe", "ja": "地球 世界 球" }
    ]
  },
  {
    "id": "audio_9",
    "name": "音声用セット 9 (801 - 900)",
    "words": [
      { "en": "assess", "ja": "を評価する を査定する" },
      { "en": "pose", "ja": "危険 を引き起こす 問題など を提起する ポーズをとる を 装う" },
      { "en": "yield", "ja": "をもたらす を に 譲る に 屈する" },
      { "en": "exhibit", "ja": "を示す 見せる を展示する" },
      { "en": "distribute", "ja": "を に 分配する 受身形で 分布する" },
      { "en": "command", "ja": "を命じる を指揮する 景色 を見渡せる" },
      { "en": "occupy", "ja": "空間 時間 を占める を占領する" },
      { "en": "pile", "ja": "を積み重ねる 積み重なる" },
      { "en": "frustrate", "ja": "をいら立たせる 計画 希望など を挫折させる" },
      { "en": "relieve", "ja": "を和らげる 受身形で して 安心する を解放する" },
      { "en": "deserve", "ja": "に値する" },
      { "en": "peer", "ja": "を じっと見る" },
      { "en": "convert", "ja": "を変える を改宗 転向 させる を交換する" },
      { "en": "boost", "ja": "を押し上げる を増加させる" },
      { "en": "endure", "ja": "に耐える に 持ちこたえる" },
      { "en": "correspond", "ja": "一致する に 相当する 文通する" },
      { "en": "impose", "ja": "を課す を押しつける" },
      { "en": "resolve", "ja": "を解決する を決意する を議決する" },
      { "en": "interrupt", "ja": "を中断させる の 邪魔をする" },
      { "en": "prohibit", "ja": "を禁止する" },
      { "en": "punish", "ja": "を罰する に損傷を与える" },
      { "en": "embrace", "ja": "を受け入れる を 抱擁する を包含する" },
      { "en": "modify", "ja": "を修正する を緩和する" },
      { "en": "enthusiasm", "ja": "への 熱情 熱意" },
      { "en": "phase", "ja": "段階 局面 側面" },
      { "en": "mode", "ja": "方式 気分 形態 流行" },
      { "en": "asteroid", "ja": "小惑星 ヒトデ" },
      { "en": "soul", "ja": "精神 魂 霊魂 生気" },
      { "en": "infection", "ja": "感染 症" },
      { "en": "grocery", "ja": "食料雑貨 食料雑貨店" },
      { "en": "instinct", "ja": "本能 勘 直感 自然に起こる 衝動" },
      { "en": "courage", "ja": "勇気" },
      { "en": "incentive", "ja": "動機 づけ 報奨金" },
      { "en": "prospect", "ja": "見込み 未来への 展望 有望な人" },
      { "en": "obstacle", "ja": "に対する 障害 物" },
      { "en": "flavor", "ja": "風味 特色" },
      { "en": "portion", "ja": "部分 人前 割り当て" },
      { "en": "luxury", "ja": "ぜいたく 品 形容詞的に 豪華な" },
      { "en": "ritual", "ja": "儀式 日常の 習慣的行為" },
      { "en": "council", "ja": "地方 議会 評議会 公の 会議" },
      { "en": "administration", "ja": "管理 部 行政 政府 機関" },
      { "en": "curriculum", "ja": "教育課程 カリキュラム" },
      { "en": "precious", "ja": "貴重な 高価な" },
      { "en": "optimistic", "ja": "楽観的な" },
      { "en": "genuine", "ja": "本物の 偽りのない" },
      { "en": "manual", "ja": "体 手 を使う 手の 手動式の" },
      { "en": "instant", "ja": "即時の すぐの 即席の" },
      { "en": "collective", "ja": "集団の 共同の" },
      { "en": "profound", "ja": "重大な 深い 難解な" },
      { "en": "steady", "ja": "着実な 一定の 安定した" },
      { "en": "mature", "ja": "成熟した 未熟な 熟した" },
      { "en": "approve", "ja": "賛成する を承認する" },
      { "en": "remark", "ja": "と述べる について 意見を述べる" },
      { "en": "pop", "ja": "ひょいと動く 不意に現れる ポンとはじける" },
      { "en": "greet", "ja": "に挨拶する を迎える" },
      { "en": "apologize", "ja": "に のことで 謝る 弁明する" },
      { "en": "derive", "ja": "由来する を引き出す を推論する" },
      { "en": "defeat", "ja": "を負かす を失敗させる" },
      { "en": "wed", "ja": "と結婚する を と 結婚させる" },
      { "en": "delight", "ja": "を喜ばせる を 大いに喜ぶ" },
      { "en": "rescue", "ja": "を救う" },
      { "en": "register", "ja": "を記録する 登録する に 登録する" },
      { "en": "rid", "ja": "から を 取り除く 除去する" },
      { "en": "compose", "ja": "を構成する を創作する を鎮静する" },
      { "en": "misunderstand", "ja": "を 誤解する" },
      { "en": "ruin", "ja": "をだめにする を破滅させる 破滅する" },
      { "en": "defend", "ja": "を防御する を弁護する" },
      { "en": "qualify", "ja": "人 に資格を与える 資格がある" },
      { "en": "passion", "ja": "情熱 熱中 激怒" },
      { "en": "span", "ja": "期間 範囲" },
      { "en": "gravity", "ja": "重力 引力 重量 重大さ" },
      { "en": "orbit", "ja": "軌道 活動 勢力などの 範囲" },
      { "en": "core", "ja": "核心 芯" },
      { "en": "nerve", "ja": "神経 神経過敏 する 度胸" },
      { "en": "mall", "ja": "主に米 モール ショッピングセンター" },
      { "en": "faith", "ja": "への 信頼 信仰 心" },
      { "en": "architecture", "ja": "建築 建築様式 構造" },
      { "en": "stem", "ja": "草木の 茎 幹" },
      { "en": "illusion", "ja": "錯覚 思い違い 幻" },
      { "en": "discrimination", "ja": "に対する 差別 区別" },
      { "en": "shame", "ja": "恥 残念なこと" },
      { "en": "drought", "ja": "干ばつ 慢性的な 不足" },
      { "en": "recipe", "ja": "調理法 レシピ 手順 秘訣" },
      { "en": "chip", "ja": "小片 破片 欠けた箇所 集積回路" },
      { "en": "sake", "ja": "で のために の目的で に免じて" },
      { "en": "prefecture", "ja": "日本の 県 府 フランスなどの 県" },
      { "en": "casual", "ja": "何気ない 形式ばらない" },
      { "en": "unpleasant", "ja": "不愉快な 不親切な 無礼な" },
      { "en": "Arctic", "ja": "北極の 南極の" },
      { "en": "ultimate", "ja": "究極の" },
      { "en": "deaf", "ja": "耳が聞こえない" },
      { "en": "mechanical", "ja": "機械の 機械的な" },
      { "en": "spare", "ja": "余分の 予備の" },
      { "en": "immune", "ja": "に対して 免疫を持つ を 免れた" },
      { "en": "harsh", "ja": "厳しい 光 色 味などが 不快な" },
      { "en": "inevitable", "ja": "避けられない" },
      { "en": "likewise", "ja": "同様に" },
      { "en": "humor", "ja": "ユーモア 気分 機嫌 気質" },
      { "en": "generous", "ja": "寛大な 気前のよい けちな 豊富な" },
      { "en": "rough", "ja": "粗い 大まかな 乱暴な" }
    ]
  },
  {
    "id": "audio_10",
    "name": "音声用セット 10 (901 - 1000)",
    "words": [
      { "en": "chase", "ja": "を 追跡する を 追求する" },
      { "en": "sue", "ja": "を告訴する を求めて 訴訟を起こす" },
      { "en": "gaze", "ja": "じっと見る" },
      { "en": "slip", "ja": "滑る 滑り落ちる そっと動く" },
      { "en": "load", "ja": "に積む に負わせる" },
      { "en": "wander", "ja": "歩き回る それる はぐれる" },
      { "en": "float", "ja": "漂う 浮かぶ を浮かべる" },
      { "en": "pronounce", "ja": "を発音する を宣言する" },
      { "en": "shrink", "ja": "縮む 縮小する 減少する ひるむ" },
      { "en": "restore", "ja": "を回復させる を修復する" },
      { "en": "trigger", "ja": "を引き起こす のきっかけとなる" },
      { "en": "grab", "ja": "をつかむ を横取りする を急いで食べる" },
      { "en": "reproduce", "ja": "を複製する を繁殖させる 繁殖する" },
      { "en": "bob", "ja": "上下に動く 急に動く を上下に動かす" },
      { "en": "entertain", "ja": "を楽しませる をもてなす" },
      { "en": "cultivate", "ja": "を養う を耕す を栽培する" },
      { "en": "regulate", "ja": "を規制する を調整する" },
      { "en": "classify", "ja": "を分類する を機密扱いにする" },
      { "en": "pause", "ja": "一時的に 中止する 一瞬 立ち止まる" },
      { "en": "lean", "ja": "傾く 寄りかかる をもたせかける" },
      { "en": "bump", "ja": "ぶつかる をぶつける" },
      { "en": "fold", "ja": "を折り畳む 両腕 を組む 折り 畳める" },
      { "en": "hesitate", "ja": "躊躇する ためらう" },
      { "en": "pump", "ja": "液体 気体 をポンプで送り込む をくみ出す を注ぎ込む" },
      { "en": "mount", "ja": "を据えつける に着手する 自転車など に乗る 増える" },
      { "en": "exceed", "ja": "を超える に勝る" },
      { "en": "confront", "ja": "に立ち向かう 困難などが に立ちはだかる" },
      { "en": "privilege", "ja": "特権 特典" },
      { "en": "neuron", "ja": "ニューロン 神経単位" },
      { "en": "panel", "ja": "専門家の 一団 討論者一同 羽目板" },
      { "en": "semester", "ja": "主に米 学期制の 学期" },
      { "en": "workforce", "ja": "労働人口 総労働力 全従業員 数" },
      { "en": "abuse", "ja": "乱用 虐待" },
      { "en": "vice", "ja": "道徳上の 悪 欠点" },
      { "en": "tragedy", "ja": "悲劇 的な事態 喜劇" },
      { "en": "scenario", "ja": "予想される 筋書き 事態 脚本" },
      { "en": "allergy", "ja": "アレルギー" },
      { "en": "antibiotic", "ja": "通例 抗生物質" },
      { "en": "vaccine", "ja": "ワクチン" },
      { "en": "metaphor", "ja": "隠喩 比喩" },
      { "en": "folk", "ja": "人々 皆さん 家族" },
      { "en": "transition", "ja": "移り変わり 過渡期" },
      { "en": "mineral", "ja": "鉱物 ミネラル" },
      { "en": "skeleton", "ja": "骨格 骨組み 概略" },
      { "en": "counterpart", "ja": "相当する物 人" },
      { "en": "stroke", "ja": "脳卒中 ボールを 打つこと 雷などの 一撃" },
      { "en": "pedestrian", "ja": "歩行者" },
      { "en": "trail", "ja": "野山などの 小道 跡 手がかり" },
      { "en": "ecology", "ja": "生態学 生態系 環境保護" },
      { "en": "sibling", "ja": "きょうだい の 人" },
      { "en": "ratio", "ja": "比率" },
      { "en": "mixture", "ja": "混合 物" },
      { "en": "charm", "ja": "魅力 お守り" },
      { "en": "ambition", "ja": "に対する 願望 野望 野心" },
      { "en": "prominent", "ja": "卓越した 目立つ" },
      { "en": "radical", "ja": "急進的な 根本的な" },
      { "en": "prompt", "ja": "即座の 迅速な" },
      { "en": "informal", "ja": "形式ばらない 略式の 正式の 言葉が くだけた" },
      { "en": "mutual", "ja": "相互の 共通の" },
      { "en": "neutral", "ja": "中立の 特徴 表情などが はっきりしない" },
      { "en": "polar", "ja": "極地の 電極の" },
      { "en": "awful", "ja": "ひどい 嫌な ものすごい" },
      { "en": "cruel", "ja": "残酷な むごい" },
      { "en": "vulnerable", "ja": "攻撃などに 弱い もろい 傷つきやすい" },
      { "en": "urgent", "ja": "緊急の" },
      { "en": "spiritual", "ja": "精神の 霊的な" },
      { "en": "nonetheless", "ja": "それにもかかわらず それでもなお" },
      { "en": "overwhelm", "ja": "を圧倒する を 精神的に 打ちのめす" },
      { "en": "pour", "ja": "を注ぐ 激しく降る 押し寄せる" },
      { "en": "substitute", "ja": "を代わりに使う の 代理をする" },
      { "en": "retain", "ja": "を保持する を覚えている" },
      { "en": "interfere", "ja": "干渉する 介入する 邪魔する" },
      { "en": "anticipate", "ja": "を予期する 楽しみに待つ" },
      { "en": "justify", "ja": "を正当化する" },
      { "en": "scan", "ja": "を走査 スキャン する をざっと見る を注意深く調べる" },
      { "en": "submit", "ja": "を提出する で に 従う" },
      { "en": "undergo", "ja": "を経験する 手術など を受ける に耐える" },
      { "en": "consult", "ja": "に 相談する を参照する" },
      { "en": "fulfill", "ja": "を実現させる を果たす を満たす" },
      { "en": "formation", "ja": "形成 構成 物 隊列" },
      { "en": "dimension", "ja": "側面 局面 次元 寸法" },
      { "en": "sensation", "ja": "感覚 大評判" },
      { "en": "chart", "ja": "図 グラフ 海図 ヒットチャート" },
      { "en": "geography", "ja": "地理 地理学" },
      { "en": "mill", "ja": "製造工場 製粉所 粉ひき機" },
      { "en": "fate", "ja": "運命 結末 最期" },
      { "en": "wound", "ja": "銃弾 刃物などによる 傷 痛手" },
      { "en": "fare", "ja": "乗り物の 料金" },
      { "en": "maximum", "ja": "最大限" },
      { "en": "galaxy", "ja": "星雲 銀河 銀河系" },
      { "en": "alert", "ja": "警戒して 敏速な" },
      { "en": "magnetic", "ja": "磁気の 磁石の 人を引きつける" },
      { "en": "fluent", "ja": "流ちょうな" },
      { "en": "external", "ja": "外部の 対外的な" },
      { "en": "passive", "ja": "受動的な 消極的な" },
      { "en": "unrelated", "ja": "無関係の 血縁関係がない" },
      { "en": "fake", "ja": "偽の 見せかけだけの" },
      { "en": "modest", "ja": "謙虚な 適度な 質素な" },
      { "en": "underlie", "ja": "の根底にある" },
      { "en": "keen", "ja": "熱心な 鋭敏な 感情 関心などが 強い" }
    ]
  },
  {
    "id": "audio_11",
    "name": "音声用セット 11 (1001 - 1100)",
    "words": [
      { "en": "negotiate", "ja": "交渉する を 交渉して 取り決める" },
      { "en": "donate", "ja": "を寄付する 臓器 血液 を提供する" },
      { "en": "tap", "ja": "を軽くたたく 液体 を出す を盗聴する" },
      { "en": "forecast", "ja": "を予想 予測 する" },
      { "en": "burst", "ja": "破裂する を 突然始める" },
      { "en": "forbid", "ja": "を禁じる" },
      { "en": "dispute", "ja": "に異議を唱える を 議論する" },
      { "en": "distract", "ja": "注意など をそらす" },
      { "en": "cheat", "ja": "をだます 不正をする" },
      { "en": "foster", "ja": "をはぐくむ を養育する を心に抱く" },
      { "en": "obey", "ja": "に従う に服従する" },
      { "en": "transmit", "ja": "を伝える 電波 信号など を送る" },
      { "en": "nod", "ja": "うなずく 会釈する うとうとする" },
      { "en": "blend", "ja": "を混ぜる を調和させる に 溶け込む" },
      { "en": "dedicate", "ja": "をささげる を献呈する" },
      { "en": "premise", "ja": "前提 建物を含めた 構内 敷地" },
      { "en": "merit", "ja": "利点 欠点 功績 真価" },
      { "en": "sympathy", "ja": "同情 に対する 共感" },
      { "en": "compliment", "ja": "賛辞 表敬" },
      { "en": "distress", "ja": "苦悩 苦痛 困窮" },
      { "en": "expedition", "ja": "遠征 隊 探検 隊" },
      { "en": "adolescent", "ja": "青年" },
      { "en": "jury", "ja": "陪審 員団 審査員団" },
      { "en": "ethic", "ja": "倫理 道徳 倫理 道徳 規範" },
      { "en": "faculty", "ja": "能力 機能 学部 教授陣" },
      { "en": "scheme", "ja": "計画 体系 陰謀" },
      { "en": "nutrition", "ja": "栄養 の摂取" },
      { "en": "particle", "ja": "微 粒子 ほんのわずか" },
      { "en": "molecule", "ja": "分子 微粒子" },
      { "en": "poll", "ja": "世論調査 投票 数" },
      { "en": "dementia", "ja": "認知症" },
      { "en": "fatigue", "ja": "疲労" },
      { "en": "pesticide", "ja": "殺虫剤 除草剤" },
      { "en": "fabric", "ja": "織物 布 地 構造" },
      { "en": "fantasy", "ja": "空想 幻想 幻想的作品" },
      { "en": "fancy", "ja": "気まぐれな 好み 空想 思いつき" },
      { "en": "virtue", "ja": "美徳 長所 効能" },
      { "en": "grateful", "ja": "感謝している" },
      { "en": "valid", "ja": "妥当な 妥当でない 有効な" },
      { "en": "elaborate", "ja": "入念な 凝った" },
      { "en": "moderate", "ja": "適度な 穏健な" },
      { "en": "brilliant", "ja": "すばらしい 才能にあふれた きらめく" },
      { "en": "innocent", "ja": "無罪の 無邪気な 無知の" },
      { "en": "subsequent", "ja": "その後の" },
      { "en": "shallow", "ja": "浅い 深い 浅薄な" },
      { "en": "indifferent", "ja": "無関心な" },
      { "en": "inferior", "ja": "より劣った よりすぐれた" },
      { "en": "awkward", "ja": "気まずい ぎこちない 厄介な" },
      { "en": "intimate", "ja": "親密な 密接な" },
      { "en": "medieval", "ja": "中世の 時代遅れの" },
      { "en": "sacred", "ja": "神聖な 宗教的な 厳粛な" },
      { "en": "simultaneously", "ja": "と 同時に 一斉に" },
      { "en": "grasp", "ja": "を把握 理解 する をしっかり握る" },
      { "en": "arrest", "ja": "を逮捕する を止める 注意 を引く" },
      { "en": "crack", "ja": "ひびが入る にひびを入れる" },
      { "en": "split", "ja": "を分割する を分担する 分裂する" },
      { "en": "exclude", "ja": "を除外する" },
      { "en": "heal", "ja": "人 傷など を治す 治る" },
      { "en": "install", "ja": "をインストールする を設置する を就任させる" },
      { "en": "cite", "ja": "を引き合いに出す を引用する" },
      { "en": "quote", "ja": "を引用する を引き合いに出す" },
      { "en": "highlight", "ja": "を目立たせる 強調する" },
      { "en": "bend", "ja": "を曲げる を屈服させる 曲がる" },
      { "en": "deprive", "ja": "から 権利などを 奪う" },
      { "en": "govern", "ja": "を 統治する 支配する" },
      { "en": "log", "ja": "で ログオンする を記録する" },
      { "en": "bully", "ja": "をいじめる を脅す" },
      { "en": "leap", "ja": "跳ぶ さっと動く 急上昇する" },
      { "en": "astonish", "ja": "を驚かす" },
      { "en": "thrill", "ja": "をぞくぞくさせる わくわくする" },
      { "en": "bow", "ja": "おじぎする 屈服する" },
      { "en": "complicate", "ja": "を複雑にする" },
      { "en": "persist", "ja": "続く 固執する" },
      { "en": "equip", "ja": "に備えつける" },
      { "en": "input", "ja": "入力 情報 投入 情報 時間などの 提供" },
      { "en": "infrastructure", "ja": "インフラ 基本的施設 経済 基盤" },
      { "en": "ray", "ja": "光線 ひらめき 一筋の光明" },
      { "en": "joint", "ja": "関節 接合 部" },
      { "en": "shade", "ja": "日 陰 色合い 日よけ 微妙な相違" },
      { "en": "penalty", "ja": "刑 罰 罰金 ペナルティー" },
      { "en": "nationality", "ja": "国籍 国民 国民性" },
      { "en": "clinic", "ja": "診療所 クリニック 病院内の 科" },
      { "en": "dilemma", "ja": "ジレンマ 板ばさみ" },
      { "en": "queue", "ja": "英 順番を待つ 列 米" },
      { "en": "curve", "ja": "道路などの カーブ 曲線" },
      { "en": "narrative", "ja": "物語 話 小説の 叙述部分 地の文" },
      { "en": "fingerprint", "ja": "指紋" },
      { "en": "file", "ja": "ファイル 書類の とじ込み" },
      { "en": "wilderness", "ja": "荒野 庭 町などの 放置された部分" },
      { "en": "panic", "ja": "パニック 状態 狼狽" },
      { "en": "dynamic", "ja": "活動的な 精力的な 動的な" },
      { "en": "brave", "ja": "勇敢な 臆病な 見事な" },
      { "en": "tremendous", "ja": "途方もない 莫大な すばらしい" },
      { "en": "oral", "ja": "口頭の" },
      { "en": "obese", "ja": "肥満した" },
      { "en": "pregnant", "ja": "妊娠した で 満ちている" },
      { "en": "diminish", "ja": "を減らす 減少する" },
      { "en": "pitch", "ja": "を投げる 倒れる 縦揺れする" },
      { "en": "versus", "ja": "で 対 か か" },
      { "en": "overlook", "ja": "を見落とす を大目に見る を見渡す" }
    ]
  },
  {
    "id": "audio_12",
    "name": "音声用セット 12 (1101 - 1200)",
    "words": [
      { "en": "reinforce", "ja": "を強化する を補強する" },
      { "en": "undertake", "ja": "を引き受ける を保証する に着手する" },
      { "en": "grip", "ja": "を握る をとらえる" },
      { "en": "dismiss", "ja": "意見など を退ける を解雇する" },
      { "en": "conceal", "ja": "を隠す を秘密にする" },
      { "en": "exaggerate", "ja": "を 誇張する を強調する" },
      { "en": "mislead", "ja": "を誤解させる 欺く 人 を間違った方向に導く" },
      { "en": "spoil", "ja": "を台無しにする を甘やかす だめになる" },
      { "en": "compound", "ja": "を悪化させる を合成する を混合する" },
      { "en": "disgust", "ja": "をむかつかせる に愛想を尽かせる" },
      { "en": "elect", "ja": "を選出する" },
      { "en": "extract", "ja": "を取り 搾り 出す を抜粋する" },
      { "en": "rear", "ja": "人 動物 植物 を育てる" },
      { "en": "congress", "ja": "米国などの 議会 会議" },
      { "en": "estate", "ja": "動産 不動産などの 財産 私有地" },
      { "en": "consensus", "ja": "総意 意見の 一致" },
      { "en": "fiber", "ja": "繊維 質 本質 精神力" },
      { "en": "scent", "ja": "よい 香り 香水" },
      { "en": "beverage", "ja": "水以外の 飲み物 飲料" },
      { "en": "diabetes", "ja": "糖尿病" },
      { "en": "reef", "ja": "岩や砂の 礁 暗礁" },
      { "en": "mess", "ja": "散らかった状態 物 混乱状態" },
      { "en": "plot", "ja": "小説などの 筋 陰謀" },
      { "en": "tablet", "ja": "タブレット 型情報端末 錠剤 平板" },
      { "en": "dense", "ja": "密集した 密度の高い 霧などが 濃い" },
      { "en": "vague", "ja": "漠然とした あいまいな おぼろげな" },
      { "en": "indigenous", "ja": "原産の 先住の その土地に 固有の" },
      { "en": "abundant", "ja": "豊富な に 富む" },
      { "en": "resort", "ja": "好ましくない手段に 訴える 頼る" },
      { "en": "bet", "ja": "と確信する 断言する 金などを かける" },
      { "en": "wipe", "ja": "を拭く を拭き取る を消し去る" },
      { "en": "compromise", "ja": "妥協する を危うくする" },
      { "en": "cue", "ja": "合図 手がかり 次の演技の キュー" },
      { "en": "caution", "ja": "用心 警告" },
      { "en": "aboriginal", "ja": "通例 アボリジニの 原生の 先住の" },
      { "en": "hybrid", "ja": "ハイブリッドの 雑種の 混成の" },
      { "en": "voluntary", "ja": "自発的な 無償の" },
      { "en": "fame", "ja": "名声" },
      { "en": "proceed", "ja": "進む 進行する を 続行する" },
      { "en": "orient", "ja": "人 を 環境などに 慣らす 受身形で 関心などが に 向いている" },
      { "en": "surf", "ja": "インターネット上の情報など を見て回る サーフィンをする" },
      { "en": "filter", "ja": "をろ過する を取り除く" },
      { "en": "bind", "ja": "を縛る を束縛する を結び付ける" },
      { "en": "accumulate", "ja": "を蓄積する 集める 積もる" },
      { "en": "advocate", "ja": "を主張する を擁護する" },
      { "en": "constitute", "ja": "を構成する になる に等しい" },
      { "en": "fade", "ja": "薄れる 衰える" },
      { "en": "chew", "ja": "を かむ をかみ砕く" },
      { "en": "swallow", "ja": "を 飲み込む をうのみにする に耐える" },
      { "en": "seal", "ja": "を密閉する に封をする" },
      { "en": "migrate", "ja": "移住する 鳥などが 渡る" },
      { "en": "accuse", "ja": "を非難する を告訴する" },
      { "en": "vanish", "ja": "消える" },
      { "en": "polish", "ja": "を磨く を洗練させる" },
      { "en": "sweep", "ja": "を 掃く を一掃する さっと通過する" },
      { "en": "explode", "ja": "爆発する 急増する を論破する" },
      { "en": "commute", "ja": "通勤 通学 する" },
      { "en": "decorate", "ja": "を装飾する" },
      { "en": "postpone", "ja": "を延期する" },
      { "en": "cease", "ja": "をやめる 終わる" },
      { "en": "inherit", "ja": "を受け継ぐ を相続する" },
      { "en": "empathy", "ja": "感情移入 共感" },
      { "en": "enterprise", "ja": "企業 事業 企画 進取の気性" },
      { "en": "output", "ja": "生産 高 出力 排出 量" },
      { "en": "millennium", "ja": "千年間 千年紀" },
      { "en": "mankind", "ja": "人類" },
      { "en": "Muslim", "ja": "イスラム教徒" },
      { "en": "landmine", "ja": "地雷" },
      { "en": "controversy", "ja": "論争" },
      { "en": "retail", "ja": "小売り 卸売り" },
      { "en": "supplement", "ja": "栄養補助剤 サプリメント 補足" },
      { "en": "province", "ja": "州 省 地方 分野" },
      { "en": "microbe", "ja": "微生物 細菌" },
      { "en": "excess", "ja": "過剰 超過" },
      { "en": "gallery", "ja": "美術館 画廊 観客 ギャラリー 回廊" },
      { "en": "deadline", "ja": "締め切り" },
      { "en": "undergraduate", "ja": "学部学生" },
      { "en": "slavery", "ja": "奴隷制度 苦役" },
      { "en": "prey", "ja": "獲物 犠牲者" },
      { "en": "recession", "ja": "不況 後退" },
      { "en": "retreat", "ja": "後退 退却 計画 決定などの 撤回" },
      { "en": "grave", "ja": "墓 通例" },
      { "en": "the", "ja": "死" },
      { "en": "column", "ja": "コラム 新聞などの 欄 円柱 縦 列" },
      { "en": "scenery", "ja": "集合的に 景色 背景" },
      { "en": "sculpture", "ja": "彫刻 作品" },
      { "en": "exotic", "ja": "外来の 異国風の" },
      { "en": "acid", "ja": "酸性の 酸っぱい 辛辣な" },
      { "en": "bitter", "ja": "苦い つらい 辛辣な 怒りっぽい" },
      { "en": "sensible", "ja": "賢明な 実用的な 顕著な" },
      { "en": "noble", "ja": "高貴な 堂々とした 高潔な" },
      { "en": "parallel", "ja": "と 平行 並行 の 類似した" },
      { "en": "tense", "ja": "張り詰めた 緊張した" },
      { "en": "vertical", "ja": "垂直の 水平な 縦方向の" },
      { "en": "seasonal", "ja": "季節の 季節的な" },
      { "en": "irrelevant", "ja": "にとって 無関係の 見当違いの" },
      { "en": "ridiculous", "ja": "ばかげた 法外な" },
      { "en": "fairy", "ja": "妖精の ような" },
      { "en": "sensory", "ja": "感覚の" },
      { "en": "chronic", "ja": "慢性の 長引く 常習の" }
    ]
  },
  {
    "id": "audio_13",
    "name": "音声用セット 13 (1201 - 1300)",
    "words": [
      { "en": "inclined", "ja": "傾向がある 傾いた" },
      { "en": "infer", "ja": "を推論する 推測する" },
      { "en": "esteem", "ja": "を尊敬する を見なす" },
      { "en": "tackle", "ja": "に取り組む と のことで 話をつける" },
      { "en": "venture", "ja": "危険を冒して進む を思い切ってする" },
      { "en": "accelerate", "ja": "を加速させる 促進する 加速する" },
      { "en": "accustom", "ja": "人 を慣れさせる" },
      { "en": "amuse", "ja": "をおもしろがらせる 楽しませる" },
      { "en": "flourish", "ja": "繁栄する 繁茂する を振りかざす" },
      { "en": "thrive", "ja": "繁栄する うまくいく 繁茂する" },
      { "en": "nurture", "ja": "をはぐくむ を養成する" },
      { "en": "click", "ja": "を クリックする をカチッと鳴らす カチッと音がする" },
      { "en": "spin", "ja": "回転する を回転させる 糸 を紡ぐ" },
      { "en": "clip", "ja": "を切り抜く を はさみで 切り取る をクリップで留める" },
      { "en": "drag", "ja": "を引きずる ぐずぐずする" },
      { "en": "cast", "ja": "を投じる に役を当てる" },
      { "en": "scatter", "ja": "をまき散らす 分散する" },
      { "en": "tempt", "ja": "を する 気にさせる を引きつける" },
      { "en": "withdraw", "ja": "を引き出す を撤回する 撤退する" },
      { "en": "yawn", "ja": "あくびをする" },
      { "en": "blink", "ja": "まばたきする 点滅する 目 をまたたく" },
      { "en": "dye", "ja": "を染める 染まる" },
      { "en": "spill", "ja": "をこぼす こぼれる" },
      { "en": "irritate", "ja": "をいらいらさせる をひりひりさせる" },
      { "en": "insult", "ja": "を侮辱する" },
      { "en": "enforce", "ja": "を施行 実施 する を に 強制する" },
      { "en": "rob", "ja": "から 金品を 奪う" },
      { "en": "drain", "ja": "液体 を流出させる 液体が 流れ出る" },
      { "en": "suspend", "ja": "を停職 停学 出場停止 にする を一時的に中断する" },
      { "en": "drift", "ja": "漂う さまよう を押し流す" },
      { "en": "forgive", "ja": "を許す を免除する" },
      { "en": "revise", "ja": "を修正する を改訂する" },
      { "en": "recruit", "ja": "を募る に新人を補充する" },
      { "en": "twist", "ja": "をねじる ひねる を歪曲する" },
      { "en": "crush", "ja": "を押しつぶす を弾圧する を絞り出す" },
      { "en": "pin", "ja": "をピンで留める を突き刺す" },
      { "en": "uncover", "ja": "を暴く を発掘する" },
      { "en": "exploit", "ja": "を活用する を搾取する につけ込む" },
      { "en": "implement", "ja": "を実行 実施 する" },
      { "en": "integrate", "ja": "を統合する 融合する" },
      { "en": "incorporate", "ja": "を取り入れる を法人にする 合併する" },
      { "en": "profile", "ja": "人物の紹介 横顔 輪郭" },
      { "en": "appetite", "ja": "食欲 欲求" },
      { "en": "impulse", "ja": "衝動 刺激" },
      { "en": "script", "ja": "台本 筆跡" },
      { "en": "anniversary", "ja": "周年 記念日" },
      { "en": "pension", "ja": "年金" },
      { "en": "temper", "ja": "気質 気性 機嫌 かんしゃく" },
      { "en": "cortex", "ja": "皮質 樹皮" },
      { "en": "syndrome", "ja": "症候群 現象" },
      { "en": "chamber", "ja": "特定の目的の 部屋 議場 議院" },
      { "en": "utility", "ja": "公共事業 公共料金 実用性" },
      { "en": "cattle", "ja": "集合的に 牛" },
      { "en": "herd", "ja": "牛などの 群れ 群衆" },
      { "en": "fluid", "ja": "流動体 液体" },
      { "en": "pity", "ja": "残念なこと 哀れみ" },
      { "en": "priest", "ja": "聖職者" },
      { "en": "acquaintance", "ja": "知人 面識 知識" },
      { "en": "offspring", "ja": "子孫 子 成果" },
      { "en": "famine", "ja": "飢饉 食糧 物資の ひどい不足" },
      { "en": "deforestation", "ja": "森林伐採" },
      { "en": "jail", "ja": "刑務所 拘置所" },
      { "en": "commodity", "ja": "商品 有用なもの" },
      { "en": "format", "ja": "書式 形式 本などの 型" },
      { "en": "recipient", "ja": "受け取る人 臓器などの 被提供者" },
      { "en": "drill", "ja": "訓練 反復 練習 ドリル 錐" },
      { "en": "inability", "ja": "無能 無力" },
      { "en": "republic", "ja": "共和国 共和制" },
      { "en": "combat", "ja": "戦闘 対立" },
      { "en": "debris", "ja": "破壊された後の 残骸 瓦礫 がらくた" },
      { "en": "bug", "ja": "病原菌 が起こす病気 虫 盗聴器 機械 プログラムの 欠陥" },
      { "en": "fraction", "ja": "わずか 一部 分数" },
      { "en": "index", "ja": "指標 索引 指数" },
      { "en": "intuition", "ja": "直観 力 直感" },
      { "en": "motive", "ja": "動機" },
      { "en": "consent", "ja": "同意 承諾" },
      { "en": "hierarchy", "ja": "社会の 階層制 支配層" },
      { "en": "monument", "ja": "記念碑 遺跡 金字塔" },
      { "en": "asset", "ja": "通例 資産 価値のあるもの 利点" },
      { "en": "decent", "ja": "まずまずの きちんとした 上品な" },
      { "en": "competent", "ja": "有能な 適任の 満足できる" },
      { "en": "straightforward", "ja": "単純な 率直な" },
      { "en": "cosmetic", "ja": "化粧の 美容の うわべの" },
      { "en": "delicate", "ja": "繊細な 扱いにくい もろい" },
      { "en": "interior", "ja": "室内の 内部の 外部の" },
      { "en": "transparent", "ja": "透明な 明快な" },
      { "en": "aesthetic", "ja": "美的な 美学の" },
      { "en": "deliberate", "ja": "故意の 慎重な" },
      { "en": "demographic", "ja": "人口統計学の" },
      { "en": "prehistoric", "ja": "有史以前の 旧式な" },
      { "en": "innate", "ja": "生まれながらの 固有の" },
      { "en": "mild", "ja": "穏やかな 程度が 軽い" },
      { "en": "toxic", "ja": "有毒な 中毒性の" },
      { "en": "ashamed", "ja": "恥じて" },
      { "en": "humble", "ja": "謙虚な 質素な 身分が低い" },
      { "en": "peculiar", "ja": "特有の 特異な" },
      { "en": "steep", "ja": "傾斜が 急な 急激な 法外な" },
      { "en": "trivial", "ja": "ささいな 取るに足りない" },
      { "en": "magnificent", "ja": "壮大な 見事な" },
      { "en": "wireless", "ja": "無線 電信 の ラジオの" }
    ]
  },
  {
    "id": "audio_14",
    "name": "音声用セット 14 (1301 - 1400)",
    "words": [
      { "en": "ongoing", "ja": "継続している 進行中の" },
      { "en": "assure", "ja": "に自信を持って言う を保証する" },
      { "en": "precede", "ja": "に先行する に優先する" },
      { "en": "revive", "ja": "を復活させる 復活する" },
      { "en": "compel", "ja": "に強いる" },
      { "en": "blossom", "ja": "花が咲く 発展する" },
      { "en": "terrify", "ja": "を怖がらせる を脅かす" },
      { "en": "violate", "ja": "法律 規則など に違反する を侵害する" },
      { "en": "suppress", "ja": "を抑える を抑圧する" },
      { "en": "deceive", "ja": "をだます" },
      { "en": "manipulate", "ja": "を 巧みに 操る を改ざんする" },
      { "en": "starve", "ja": "飢える を 渇望する を飢えさせる" },
      { "en": "flee", "ja": "から 逃げる" },
      { "en": "whisper", "ja": "を ささやく" },
      { "en": "yell", "ja": "叫ぶ どなる" },
      { "en": "deposit", "ja": "を置く を預ける を堆積させる" },
      { "en": "confine", "ja": "を限定する 通例受身形で 閉じ込められる" },
      { "en": "swing", "ja": "を揺らす 振る 揺れる 行動に さっと移る" },
      { "en": "prolong", "ja": "を長引かせる" },
      { "en": "depict", "ja": "を描く" },
      { "en": "outline", "ja": "の要点を述べる の輪郭を描く" },
      { "en": "shed", "ja": "を捨て去る 光など を放つ 涙 血 を流す" },
      { "en": "emit", "ja": "光 熱など を出す 排出する 信号 を送る" },
      { "en": "renew", "ja": "を更新する 資源 を再生する" },
      { "en": "utilize", "ja": "を利用する" },
      { "en": "assert", "ja": "を主張する" },
      { "en": "strain", "ja": "に負担をかける を緊張させる を漉す" },
      { "en": "strive", "ja": "努力する 争う" },
      { "en": "dare", "ja": "あえて 思い切って する" },
      { "en": "boast", "ja": "を誇る を 自慢する" },
      { "en": "startle", "ja": "をびっくりさせる" },
      { "en": "offend", "ja": "の気分を害する に 違反する" },
      { "en": "compute", "ja": "を 計算する コンピューターを使う" },
      { "en": "assemble", "ja": "を集める を組み立てる 集まる" },
      { "en": "worsen", "ja": "を悪化させる 悪化する" },
      { "en": "flip", "ja": "を ぱっと 裏返す を軽くはじく" },
      { "en": "rub", "ja": "を こする に を塗る" },
      { "en": "descend", "ja": "を 降りる 受け継がれる" },
      { "en": "compensate", "ja": "補償する に償う" },
      { "en": "comprise", "ja": "から成る を構成する" },
      { "en": "prevail", "ja": "普及している 支配的である に 打ち勝つ" },
      { "en": "quest", "ja": "探究" },
      { "en": "dignity", "ja": "尊厳 威厳" },
      { "en": "criterion", "ja": "判断 評価の 基準" },
      { "en": "paradox", "ja": "逆説 矛盾" },
      { "en": "parliament", "ja": "英国などの 議会 国会議員 団" },
      { "en": "legislation", "ja": "法律 立法" },
      { "en": "agenda", "ja": "協議事項 リスト 議事日程 表 政治上の 課題" },
      { "en": "mainstream", "ja": "活動 思潮などの 主流 大勢" },
      { "en": "troop", "ja": "軍隊 集団" },
      { "en": "epidemic", "ja": "流行 病 蔓延" },
      { "en": "outbreak", "ja": "発生 勃発" },
      { "en": "chaos", "ja": "混沌 大混乱" },
      { "en": "nightmare", "ja": "悪夢 のような状況 不安感" },
      { "en": "horror", "ja": "恐怖 強い嫌悪 嫌な物 人" },
      { "en": "cluster", "ja": "集団 植物の 房 束" },
      { "en": "pollen", "ja": "花粉" },
      { "en": "hive", "ja": "ミツバチの巣 箱 人の集まる所" },
      { "en": "irrigation", "ja": "灌漑" },
      { "en": "dose", "ja": "薬の 回分の 服用量 放射線の 回の照射量" },
      { "en": "suicide", "ja": "自殺 自殺的行為" },
      { "en": "feast", "ja": "祝宴 大ごちそう 楽しみ" },
      { "en": "cuisine", "ja": "独特の 料理 料理法" },
      { "en": "rumor", "ja": "うわさ" },
      { "en": "proverb", "ja": "ことわざ" },
      { "en": "signature", "ja": "署名 特徴" },
      { "en": "formula", "ja": "方法 解決策 公式" },
      { "en": "tuition", "ja": "主に米 授業料 英" },
      { "en": "tuition", "ja": "個人 指導" },
      { "en": "intake", "ja": "摂取量 受け入れ数 取り入れること" },
      { "en": "spectrum", "ja": "スペクトル 波動 変動の 範囲" },
      { "en": "kidney", "ja": "腎臓" },
      { "en": "gear", "ja": "用具 一式 器具 歯車 ギア" },
      { "en": "aisle", "ja": "座席間などの 通路" },
      { "en": "grief", "ja": "深い悲しみ" },
      { "en": "destiny", "ja": "運命" },
      { "en": "skull", "ja": "頭骨 頭蓋骨 頭脳" },
      { "en": "tomb", "ja": "墓" },
      { "en": "monk", "ja": "修道士 僧 修道女 尼" },
      { "en": "worship", "ja": "崇拝 礼拝 式 賛美" },
      { "en": "outstanding", "ja": "際立った 未払いの 未解決の" },
      { "en": "unprecedented", "ja": "前例のない 空前の" },
      { "en": "infinite", "ja": "無限の 有限の 無数の" },
      { "en": "worthwhile", "ja": "価値がある 立派な" },
      { "en": "indispensable", "ja": "不可欠な なくてもすむ" },
      { "en": "compulsory", "ja": "義務的な 強制的な" },
      { "en": "probable", "ja": "十分にありそうな" },
      { "en": "ambiguous", "ja": "あいまいな 多義的な" },
      { "en": "obscure", "ja": "世に 知られていない 不明瞭な" },
      { "en": "skeptical", "ja": "に 懐疑的な" },
      { "en": "fragile", "ja": "壊れやすい 虚弱な" },
      { "en": "static", "ja": "静的な 動きのない" },
      { "en": "gradual", "ja": "徐々の 緩やかな" },
      { "en": "vocal", "ja": "声の 発声の はっきりものを言う" },
      { "en": "vivid", "ja": "鮮やかな 生き生きとした" },
      { "en": "imperial", "ja": "帝国の 皇帝の" },
      { "en": "hostile", "ja": "敵意のある 友好的な" },
      { "en": "superficial", "ja": "表面的な" },
      { "en": "scarce", "ja": "乏しい 珍しい" },
      { "en": "gross", "ja": "総計の 甚だしい 粗野な" }
    ]
  },
  {
    "id": "audio_15",
    "name": "音声用セット 15 (1401 - 1500)",
    "words": [
      { "en": "inherent", "ja": "生来の 本来的に備わっている" },
      { "en": "notable", "ja": "注目に値する 著名な" },
      { "en": "update", "ja": "を最新のものにする をアップデートする" },
      { "en": "refresh", "ja": "気分 をさわやかにする 記憶など を新たにする を最新のものにする" },
      { "en": "bloom", "ja": "花が咲く 栄える" },
      { "en": "conquer", "ja": "を征服する を克服する" },
      { "en": "induce", "ja": "を引き起こす を説得する" },
      { "en": "attain", "ja": "を獲得する 達成する に達する" },
      { "en": "spray", "ja": "を吹きかける に吹きつける" },
      { "en": "retrieve", "ja": "情報 を検索する を取り戻す を回復する" },
      { "en": "portray", "ja": "を描く の役 を演じる" },
      { "en": "scratch", "ja": "を引っかく を取り消す 削除する" },
      { "en": "designate", "ja": "を指定する を任命する" },
      { "en": "contradict", "ja": "と矛盾する に反対意見を言う" },
      { "en": "sigh", "ja": "ため息をつく" },
      { "en": "disrupt", "ja": "を混乱させる を分裂させる" },
      { "en": "depart", "ja": "出発する から それる" },
      { "en": "navigate", "ja": "を 誘導する を 操縦する を 航行する" },
      { "en": "beg", "ja": "に を 切に頼む を 懇願する" },
      { "en": "inhabit", "ja": "に住んでいる に宿る 存する" },
      { "en": "diagnose", "ja": "を 診断する" },
      { "en": "comprehend", "ja": "を理解する" },
      { "en": "oblige", "ja": "に義務づける に恩恵を施す" },
      { "en": "cram", "ja": "に詰め込む 詰め込み勉強をする" },
      { "en": "flock", "ja": "群がる 集まる" },
      { "en": "underestimate", "ja": "を 過小評価する を 過大評価する を 軽く見る を少なく見積もる" },
      { "en": "clarify", "ja": "を明確にする" },
      { "en": "spark", "ja": "を引き起こす を刺激する スパークする" },
      { "en": "seize", "ja": "をつかむ を奪い取る を没収する" },
      { "en": "soar", "ja": "急上昇する 空高く飛ぶ" },
      { "en": "glow", "ja": "光り 照り 輝く 赤く燃える 紅潮する" },
      { "en": "disguise", "ja": "を に 変装させる を偽る" },
      { "en": "distort", "ja": "を歪める 歪む" },
      { "en": "undermine", "ja": "を徐々にむしばむ を侵食する" },
      { "en": "abolish", "ja": "を廃止する" },
      { "en": "strip", "ja": "を から 取り去る を裸にする" },
      { "en": "dispose", "ja": "で を処分する を する 気にさせる を配置する" },
      { "en": "dump", "ja": "を投棄する をどさっと落とす" },
      { "en": "weave", "ja": "を織る 計画 物語など を作り上げる" },
      { "en": "refine", "ja": "を洗練する を精製する" },
      { "en": "enrich", "ja": "を豊かにする 物質 を濃縮化する" },
      { "en": "coordinate", "ja": "を調整する を組織する 服など をコーディネートする" },
      { "en": "headline", "ja": "新聞などの 見出し" },
      { "en": "internship", "ja": "米 実務 医学 研修 研修期間" },
      { "en": "outlet", "ja": "直売店 特売店 はけ口 米 電気の コンセント 英" },
      { "en": "remedy", "ja": "治療 法 治療薬 解決法" },
      { "en": "pill", "ja": "錠剤 丸薬 ピル 経口避妊薬" },
      { "en": "reception", "ja": "反応 宴会 受付 受信 状態" },
      { "en": "transaction", "ja": "商 取引 人と人との 交流" },
      { "en": "mutation", "ja": "突然変異 体 変化" },
      { "en": "dairy", "ja": "集合的に 乳製品 乳製品加工所 販売者" },
      { "en": "compassion", "ja": "同情" },
      { "en": "posture", "ja": "姿勢 心構え" },
      { "en": "curse", "ja": "悪態 ののしりの言葉 呪い 通例" },
      { "en": "a", "ja": "災い" },
      { "en": "funeral", "ja": "葬式" },
      { "en": "census", "ja": "国勢調査 交通調査" },
      { "en": "encyclopedia", "ja": "百科事典" },
      { "en": "cereal", "ja": "通例 穀物 シリアル 穀物加工食品" },
      { "en": "fragment", "ja": "断片" },
      { "en": "patch", "ja": "の 部分 斑点 継ぎ 貼り薬" },
      { "en": "rubbish", "ja": "英 ごみ 米 つまらないもの" },
      { "en": "maze", "ja": "迷路 複雑に込み入ったもの" },
      { "en": "outlook", "ja": "見解 見通し 眺め" },
      { "en": "breakthrough", "ja": "大発見 飛躍的進歩" },
      { "en": "triumph", "ja": "勝利 勝利の喜び 偉業" },
      { "en": "ally", "ja": "同盟国 提携者 援助者 盟友" },
      { "en": "spectator", "ja": "試合などの 観客" },
      { "en": "sphere", "ja": "領域 球体 天体" },
      { "en": "county", "ja": "米 郡 英 州" },
      { "en": "behalf", "ja": "利益 味方" },
      { "en": "interval", "ja": "時間の 間隔 合間 隔たり 小休止" },
      { "en": "circulation", "ja": "循環 流通 新聞 雑誌の 発行部数" },
      { "en": "blade", "ja": "刃 プロペラなどの 羽根 草などの 葉" },
      { "en": "theft", "ja": "窃盗 罪" },
      { "en": "vacuum", "ja": "真空 空虚" },
      { "en": "collision", "ja": "衝突 対立" },
      { "en": "bargain", "ja": "買い得品 取引 契約" },
      { "en": "landmark", "ja": "ある場所の 目印 画期的な出来事" },
      { "en": "revenue", "ja": "歳入 歳出 収益" },
      { "en": "treaty", "ja": "国家間の 条約 協定" },
      { "en": "supreme", "ja": "最高の" },
      { "en": "thorough", "ja": "徹底的な まったくの" },
      { "en": "naked", "ja": "裸の" },
      { "en": "sincere", "ja": "心からの 誠実な" },
      { "en": "tame", "ja": "飼いならされた 人に慣れた 退屈な" },
      { "en": "insufficient", "ja": "不十分な 不適当な" },
      { "en": "dim", "ja": "薄暗い ぼんやりした" },
      { "en": "acute", "ja": "痛み 感情などが 激しい 知覚などが 鋭い 急性の" },
      { "en": "disabled", "ja": "障害のある 障害者用の" },
      { "en": "metropolitan", "ja": "大都市の 首都圏の" },
      { "en": "monetary", "ja": "金銭的な 金融の" },
      { "en": "alternate", "ja": "代わりの 交互の" },
      { "en": "partial", "ja": "部分的な 不公平な 公平な" },
      { "en": "divine", "ja": "神の 神にささげる" },
      { "en": "drastic", "ja": "徹底的な 抜本的な 極端な" },
      { "en": "fierce", "ja": "猛烈な どう猛な" },
      { "en": "sole", "ja": "唯一の 単独の 独占的な" },
      { "en": "spontaneous", "ja": "自然発生的な 自発的な" },
      { "en": "spatial", "ja": "空間の" }
    ]
  },
  {
    "id": "audio_16",
    "name": "音声用セット 16 (1501 - 1600)",
    "words": [
      { "en": "neat", "ja": "きちんとした 見事な" },
      { "en": "tidy", "ja": "きちんとした 整頓された 相当の" },
      { "en": "loyal", "ja": "に 忠実な 誠実な" },
      { "en": "bless", "ja": "に恩恵を与える に感謝する" },
      { "en": "regain", "ja": "を取り戻す" },
      { "en": "conform", "ja": "順応する 一致する" },
      { "en": "enroll", "ja": "登録する 入会する を登録させる" },
      { "en": "entitle", "ja": "に権利を与える に題名をつける" },
      { "en": "halt", "ja": "を止める 止まる" },
      { "en": "provoke", "ja": "感情 行動など を引き起こす を挑発する" },
      { "en": "invade", "ja": "を侵略する を侵害する 場所 に殺到する" },
      { "en": "squeeze", "ja": "押し入る を押し込む を 搾る を 強く押す" },
      { "en": "crawl", "ja": "はう ゆっくり進む" },
      { "en": "digest", "ja": "を消化する を理解する を要約する" },
      { "en": "utter", "ja": "声 を発する 考えなど を述べる" },
      { "en": "refrain", "ja": "控える" },
      { "en": "populate", "ja": "に住む の住民である に人を住まわせる" },
      { "en": "accommodate", "ja": "を収容する を に 適応させる" },
      { "en": "steer", "ja": "を 操縦する を へ 向ける" },
      { "en": "drown", "ja": "溺死する を水浸しにする" },
      { "en": "dip", "ja": "を浸す 手など を に 突っ込む 下がる" },
      { "en": "soak", "ja": "を浸す をずぶぬれにする 浸る" },
      { "en": "stir", "ja": "をかき回す を揺り動かす" },
      { "en": "transplant", "ja": "を移植する を移住させる" },
      { "en": "reassure", "ja": "を安心させる" },
      { "en": "resume", "ja": "を 再開する を取り戻す" },
      { "en": "speculate", "ja": "と 推測する 投機する" },
      { "en": "surpass", "ja": "を上回る" },
      { "en": "appoint", "ja": "を任命する 日時 場所など を指定する" },
      { "en": "intrigue", "ja": "に興味を持たせる 陰謀を企てる" },
      { "en": "decay", "ja": "腐敗する 徐々に 衰える" },
      { "en": "contaminate", "ja": "を汚染する を堕落させる" },
      { "en": "swell", "ja": "膨張する 腫れる を膨らませる" },
      { "en": "delete", "ja": "を削除する 消す" },
      { "en": "tolerate", "ja": "を許容する 我慢する" },
      { "en": "envy", "ja": "をうらやむ" },
      { "en": "pray", "ja": "を 祈る" },
      { "en": "confess", "ja": "を 告白する" },
      { "en": "resign", "ja": "を 辞任する を放棄する" },
      { "en": "dissolve", "ja": "を 溶かす 議会など を解散する 契約など を解消する 溶ける" },
      { "en": "unfold", "ja": "閉じたもの を開く を明らかにする 開く 明らかになる" },
      { "en": "awaken", "ja": "を目覚めさせる から 覚める" },
      { "en": "conceive", "ja": "を 思いつく と想像する を 妊娠する" },
      { "en": "entrepreneur", "ja": "起業家 事業家" },
      { "en": "stake", "ja": "利害関係 通例 賭け金 杭" },
      { "en": "surplus", "ja": "余剰 不足 過剰 黒字" },
      { "en": "inflation", "ja": "インフレ ーション 物価の 高騰" },
      { "en": "sweatshop", "ja": "搾取工場" },
      { "en": "clash", "ja": "衝突 対立 かち合うこと ガチャンという音" },
      { "en": "sociology", "ja": "社会学" },
      { "en": "ideology", "ja": "イデオロギー 思想傾向" },
      { "en": "margin", "ja": "余白 差 利ざや" },
      { "en": "realm", "ja": "領域 領土" },
      { "en": "domain", "ja": "分野 領域 ドメイン" },
      { "en": "algorithm", "ja": "アルゴリズム 問題解決の手順" },
      { "en": "prairie", "ja": "大草原" },
      { "en": "frontier", "ja": "通例" },
      { "en": "the", "ja": "最先端 米 辺境地 国境" },
      { "en": "bullet", "ja": "銃弾" },
      { "en": "shield", "ja": "盾 防御物" },
      { "en": "despair", "ja": "絶望" },
      { "en": "radiation", "ja": "放射能 放射線" },
      { "en": "placebo", "ja": "偽薬 プラシーボ 気休め" },
      { "en": "nursery", "ja": "託児所 苗床" },
      { "en": "spouse", "ja": "配偶者" },
      { "en": "makeup", "ja": "化粧 化粧品 構成 性質" },
      { "en": "mummy", "ja": "ミイラ 英 ママ お母さん 米" },
      { "en": "flesh", "ja": "人 動物の 肉 果肉" },
      { "en": "limb", "ja": "手足" },
      { "en": "odor", "ja": "におい 気配" },
      { "en": "laundry", "ja": "洗濯 物 クリーニング店" },
      { "en": "tide", "ja": "潮 の干満 動向" },
      { "en": "questionnaire", "ja": "アンケート" },
      { "en": "nonsense", "ja": "ばかげた物 話 考え 無意味な言葉" },
      { "en": "revenge", "ja": "復讐" },
      { "en": "intellect", "ja": "知性 知識人" },
      { "en": "hospitality", "ja": "親切なもてなし 歓待 受容性" },
      { "en": "librarian", "ja": "司書 図書館員" },
      { "en": "manuscript", "ja": "手書きの 原稿 写本" },
      { "en": "obsession", "ja": "考えなどに 取りつかれること 妄想 強迫観念" },
      { "en": "hygiene", "ja": "衛生 状態 健康法" },
      { "en": "paradigm", "ja": "理論的枠組み パラダイム 模範" },
      { "en": "legitimate", "ja": "合法的な 妥当な" },
      { "en": "authentic", "ja": "本物の 信頼できる" },
      { "en": "empirical", "ja": "経験的な 経験主義の" },
      { "en": "immense", "ja": "膨大な" },
      { "en": "absurd", "ja": "ばかげた 不合理な" },
      { "en": "weird", "ja": "異様な 奇妙な" },
      { "en": "accidental", "ja": "偶然の 過失による" },
      { "en": "uneasy", "ja": "不安な 落ち着かない ぎこちない" },
      { "en": "jealous", "ja": "嫉妬深い 用心深い" },
      { "en": "feminine", "ja": "女らしい" },
      { "en": "swift", "ja": "素早い" },
      { "en": "hollow", "ja": "空洞の 空虚な うわべだけの" },
      { "en": "crude", "ja": "大まかな 粗野な 未精製の" },
      { "en": "sore", "ja": "痛い 腹が立って" },
      { "en": "pessimistic", "ja": "悲観的な" },
      { "en": "vain", "ja": "無駄な うぬぼれた" },
      { "en": "susceptible", "ja": "の 影響を受けやすい 感染しやすい" },
      { "en": "edible", "ja": "食用の 食べられる" }
    ]
  },
  {
    "id": "audio_17",
    "name": "音声用セット 17 (1601 - 1700)",
    "words": [
      { "en": "sheer", "ja": "純然たる 真の すごい 布が 薄地の" },
      { "en": "explicit", "ja": "明白な 率直な" },
      { "en": "prone", "ja": "に なりやすい する 傾向がある" },
      { "en": "affluent", "ja": "裕福な 豊富な" },
      { "en": "collaborate", "ja": "共同して働く に 協力する" },
      { "en": "exert", "ja": "を及ぼす 力など を行使する" },
      { "en": "excel", "ja": "で 秀でている に勝る" },
      { "en": "prosper", "ja": "栄える 成功する 繁殖する" },
      { "en": "surge", "ja": "殺到する 感情が こみ上げる 急騰する" },
      { "en": "intervene", "ja": "に 介入する 介在する" },
      { "en": "insert", "ja": "を挿入する" },
      { "en": "overtake", "ja": "を追い抜く に追いつく 災難 強い感情などが を襲う" },
      { "en": "snap", "ja": "をパチンと鳴らす をポキッと折る ポキッと折れる パチンと音を立てる" },
      { "en": "carve", "ja": "を彫る を切り開く 肉 を切り分ける" },
      { "en": "addict", "ja": "受身形で の 中毒になる に 凝る" },
      { "en": "condemn", "ja": "を非難する 受身形で の刑を 宣告される" },
      { "en": "convict", "ja": "に有罪を宣告する" },
      { "en": "dictate", "ja": "を指図する を書き取らせる を規定する" },
      { "en": "prescribe", "ja": "薬など を処方する を規定する" },
      { "en": "inhibit", "ja": "を抑制する を妨げる" },
      { "en": "stray", "ja": "はぐれる 道に 迷う" },
      { "en": "roam", "ja": "を 歩き回る 放浪する" },
      { "en": "enclose", "ja": "を同封する を取り囲む" },
      { "en": "execute", "ja": "を実行する を処刑する" },
      { "en": "coincide", "ja": "同時に起こる 一致する" },
      { "en": "lag", "ja": "遅れる 徐々に弱まる" },
      { "en": "cling", "ja": "しがみつく くっつく" },
      { "en": "erase", "ja": "を消す" },
      { "en": "grind", "ja": "穀物など をひく" },
      { "en": "knit", "ja": "を編む を結合する 編み物をする" },
      { "en": "inquire", "ja": "を 尋ねる" },
      { "en": "betray", "ja": "をうっかり表す を裏切る" },
      { "en": "leak", "ja": "漏れる を漏らす" },
      { "en": "smash", "ja": "を粉砕する を強打する 粉々に壊れる 激突する" },
      { "en": "bounce", "ja": "跳ねる 反射する を弾ませる メールが 宛先不明で 返送される" },
      { "en": "sprawl", "ja": "都市などが 不規則に広がる だらしなく手足を伸ばす" },
      { "en": "converse", "ja": "と 会話をする" },
      { "en": "recite", "ja": "を暗唱する を詳述する" },
      { "en": "disregard", "ja": "を無視する を軽視する" },
      { "en": "frown", "ja": "眉をひそめる" },
      { "en": "evoke", "ja": "を呼び起こす" },
      { "en": "pledge", "ja": "を誓う 約束する を与えることを約束する" },
      { "en": "aspire", "ja": "を 熱望する" },
      { "en": "contemplate", "ja": "を 熟考する を予想する" },
      { "en": "grace", "ja": "優美 優雅 分別 神の 恩寵" },
      { "en": "enlightenment", "ja": "啓蒙 啓発" },
      { "en": "commerce", "ja": "商業 貿易" },
      { "en": "draft", "ja": "下書き 為替手形 隙間風" },
      { "en": "barrel", "ja": "バレル 液量の単位 たる" },
      { "en": "timber", "ja": "英 木材 米 樹木" },
      { "en": "garment", "ja": "衣服" },
      { "en": "thread", "ja": "糸 議論などの 筋道" },
      { "en": "cabinet", "ja": "しばしば" },
      { "en": "the", "ja": "内閣 戸棚" },
      { "en": "bureau", "ja": "官庁の 局 事務局 案内所" },
      { "en": "autonomy", "ja": "個人の 自律 自治 権 自治体" },
      { "en": "toll", "ja": "損害 の程度 死傷者数 通行料" },
      { "en": "discourse", "ja": "話し合い 会話 講演 論説" },
      { "en": "superstition", "ja": "迷信" },
      { "en": "glimpse", "ja": "ちらりと見えること" },
      { "en": "arithmetic", "ja": "計算 算数" },
      { "en": "glossary", "ja": "用語小辞典 用語集" },
      { "en": "archive", "ja": "しばしば 記録文書 公文書 公文書保管所 コンピューターの アーカイブ" },
      { "en": "legacy", "ja": "遺産" },
      { "en": "anthropology", "ja": "人類学" },
      { "en": "rage", "ja": "激怒 猛威" },
      { "en": "sorrow", "ja": "悲しみ" },
      { "en": "psychiatrist", "ja": "精神科医" },
      { "en": "ward", "ja": "行政区 病棟" },
      { "en": "stall", "ja": "露店 エンスト 失速" },
      { "en": "flame", "ja": "炎 情熱" },
      { "en": "moisture", "ja": "水分 湿気" },
      { "en": "irony", "ja": "皮肉" },
      { "en": "warrior", "ja": "戦士" },
      { "en": "astronomy", "ja": "天文学" },
      { "en": "probe", "ja": "無人 宇宙探査機 の 精査 探り針" },
      { "en": "altitude", "ja": "高度 標高" },
      { "en": "tumor", "ja": "腫瘍 腫れ物" },
      { "en": "defect", "ja": "欠陥 不足" },
      { "en": "sanitation", "ja": "公衆衛生 学 下水 衛生 設備" },
      { "en": "longevity", "ja": "長寿 寿命 長年勤続" },
      { "en": "scope", "ja": "活動 能力などの 範囲 余地" },
      { "en": "sentiment", "ja": "感情 感想 感傷" },
      { "en": "plausible", "ja": "もっともらしい" },
      { "en": "vigorous", "ja": "精力的な 激しい 活力のある" },
      { "en": "masculine", "ja": "男らしい" },
      { "en": "rigid", "ja": "厳しい 硬直した" },
      { "en": "adverse", "ja": "不都合な 逆の" },
      { "en": "coherent", "ja": "一貫した 筋の通った 結束した" },
      { "en": "literal", "ja": "文字どおりの 逐語的な 散文的な" },
      { "en": "arbitrary", "ja": "恣意的な 独断的な" },
      { "en": "anonymous", "ja": "匿名の" },
      { "en": "antique", "ja": "骨董の アンティークの 古風な" },
      { "en": "eternal", "ja": "永遠の 不変の" },
      { "en": "intermediate", "ja": "中級の 中間の" },
      { "en": "subordinate", "ja": "より 下位の 副次的な" },
      { "en": "gloomy", "ja": "陰気な 薄暗い 悲観的な" },
      { "en": "thermal", "ja": "熱の 熱による 保温用の" },
      { "en": "faint", "ja": "かすかな めまいがする 弱々しい" },
      { "en": "naive", "ja": "お人よしの 愚直な 純朴な" }
    ]
  },
  {
    "id": "audio_18",
    "name": "音声用セット 18 (1701 - 1800)",
    "words": [
      { "en": "apt", "ja": "する 傾向がある 適切な 利発な" },
      { "en": "arrogant", "ja": "横柄な 傲慢な" },
      { "en": "extrovert", "ja": "外向的な 社交的な" },
      { "en": "conspicuous", "ja": "目立つ" },
      { "en": "intact", "ja": "損なわれていない 手つかずの" },
      { "en": "embody", "ja": "を具現する を包含する" },
      { "en": "illuminate", "ja": "を照らす を解明する" },
      { "en": "console", "ja": "を慰める" },
      { "en": "verify", "ja": "の正しさを証明 確認 する" },
      { "en": "disclose", "ja": "を公表する 暴く" },
      { "en": "stack", "ja": "を積む 積み重ねる で 車が 渋滞する" },
      { "en": "rotate", "ja": "回転する 循環する を回転させる" },
      { "en": "constrain", "ja": "に することを 強いる を抑える" },
      { "en": "hinder", "ja": "を妨げる" },
      { "en": "withstand", "ja": "に耐える" },
      { "en": "tweet", "ja": "を ツイートする つぶやく" },
      { "en": "sneeze", "ja": "くしゃみをする" },
      { "en": "erupt", "ja": "火山が 噴火する 勃発する" },
      { "en": "blur", "ja": "をぼかす を曇らせる をあいまいにする" },
      { "en": "overlap", "ja": "一部 重なる と 重複 共通 する" },
      { "en": "embed", "ja": "通例受身形で 埋め込まれる はめ込まれる" },
      { "en": "displace", "ja": "に取って代わる を移動させる" },
      { "en": "render", "ja": "を ある状態に する 援助など を与える" },
      { "en": "plunge", "ja": "に を 突っ込む 没頭する 陥る" },
      { "en": "surrender", "ja": "を放棄する 引き渡す に 屈する" },
      { "en": "plug", "ja": "で のプラグを電源に差し込む を で ふさぐ" },
      { "en": "suck", "ja": "を 吸う を しゃぶる" },
      { "en": "mock", "ja": "をばかにする のまねをしてからかう" },
      { "en": "tease", "ja": "を からかう をいじめる" },
      { "en": "soothe", "ja": "をなだめる を和らげる" },
      { "en": "stain", "ja": "を汚す に着色する" },
      { "en": "shun", "ja": "を避ける" },
      { "en": "stumble", "ja": "よろけながら歩く に つまずく" },
      { "en": "flush", "ja": "を紅潮させる を水で流す 紅潮する" },
      { "en": "impair", "ja": "を損なう" },
      { "en": "presume", "ja": "と思う と推定する を前提とする" },
      { "en": "contend", "ja": "と主張する 競う" },
      { "en": "roar", "ja": "うなる ほえる 大笑いする" },
      { "en": "haunt", "ja": "記憶 考えなどが につきまとう 幽霊などが に出る によく行く" },
      { "en": "divert", "ja": "注意など をそらす を迂回させる 資金など を転用する" },
      { "en": "await", "ja": "を待つ" },
      { "en": "fetch", "ja": "を 行って 持って 連れて くる" },
      { "en": "unify", "ja": "を統合 統一 する 統一される" },
      { "en": "inspect", "ja": "を点検する を視察する" },
      { "en": "entail", "ja": "を伴う 引き起こす すること を含む" },
      { "en": "tactics", "ja": "作戦 方策 戦術 戦法" },
      { "en": "feat", "ja": "偉業 功績 妙技" },
      { "en": "prestige", "ja": "名声 形容詞的に 名声のある" },
      { "en": "analogy", "ja": "類推 類似" },
      { "en": "conscience", "ja": "良心 分別" },
      { "en": "textile", "ja": "織物 繊維 産業" },
      { "en": "deficit", "ja": "赤字 不足 欠陥" },
      { "en": "plague", "ja": "疫病 害虫などの 異常発生" },
      { "en": "hazard", "ja": "危険 要素 偶然" },
      { "en": "metabolism", "ja": "新陳 代謝 代謝作用" },
      { "en": "paralysis", "ja": "麻痺 比喩的に 麻痺 状態" },
      { "en": "grid", "ja": "電気などの 供給網 格子 模様 碁盤目" },
      { "en": "carriage", "ja": "馬車 車両 米 立ち居振舞い 英 輸送" },
      { "en": "friction", "ja": "不和 摩擦" },
      { "en": "rebel", "ja": "反逆者" },
      { "en": "regime", "ja": "政権 政体 体制" },
      { "en": "monopoly", "ja": "独占 権" },
      { "en": "staple", "ja": "必需食品 主要産物" },
      { "en": "merchandise", "ja": "商品" },
      { "en": "vendor", "ja": "物売り 行商人 自動販売機" },
      { "en": "supervisor", "ja": "監督者 指導教員" },
      { "en": "predecessor", "ja": "前任者 後継者 前のもの" },
      { "en": "personnel", "ja": "集合的に 職員 社員" },
      { "en": "vessel", "ja": "船舶 容器 体液が通る 脈管" },
      { "en": "liver", "ja": "肝臓" },
      { "en": "duration", "ja": "時間の 継続 持続 時間" },
      { "en": "certificate", "ja": "証明書 免許状" },
      { "en": "geometry", "ja": "幾何学" },
      { "en": "symmetry", "ja": "左右 対称 非対称 調和" },
      { "en": "biography", "ja": "伝記" },
      { "en": "masterpiece", "ja": "傑作" },
      { "en": "rhyme", "ja": "押韻詩 韻 通例 詩歌" },
      { "en": "premium", "ja": "保険料 プレミア 景品" },
      { "en": "breakdown", "ja": "崩壊 神経 衰弱 故障 内訳" },
      { "en": "courtesy", "ja": "礼儀正しさ 好意 優遇" },
      { "en": "protocol", "ja": "条約 議定書 外交儀礼 プロトコル" },
      { "en": "specimen", "ja": "標本 実例" },
      { "en": "thesis", "ja": "論文 命題 テーゼ" },
      { "en": "eligible", "ja": "適格の 資格のある 結婚相手として 望ましい" },
      { "en": "intrinsic", "ja": "固有の 本質的な 非本質的な" },
      { "en": "diligent", "ja": "勤勉な 入念な" },
      { "en": "vocational", "ja": "職業の 職業訓練の ための" },
      { "en": "bankrupt", "ja": "破産宣告を受けた 破綻している" },
      { "en": "stern", "ja": "厳しい いかめしい" },
      { "en": "stubborn", "ja": "頑固な 強情な 手に負えない" },
      { "en": "maternal", "ja": "母の 母親らしい 父の 妊婦の" },
      { "en": "fertile", "ja": "肥沃な 不毛の 多産の" },
      { "en": "ripe", "ja": "熟した 成熟した" },
      { "en": "stiff", "ja": "硬直した 凝った 堅い" },
      { "en": "obsolete", "ja": "廃れた 使われなくなった 古くなった" },
      { "en": "vacant", "ja": "空いている" },
      { "en": "acoustic", "ja": "音響の 聴覚の 楽器が アコースティックの" },
      { "en": "preliminary", "ja": "予備の 準備の" },
      { "en": "approximate", "ja": "おおよその" },
      { "en": "implicit", "ja": "暗黙の 内在する" }
    ]
  },
  {
    "id": "audio_19",
    "name": "音声用セット 19 (1801 - 1900)",
    "words": [
      { "en": "punctual", "ja": "時間を守る" },
      { "en": "compatible", "ja": "矛盾しない 互換性のある 気が合う" },
      { "en": "ample", "ja": "十分すぎるほどの 広い" },
      { "en": "pervasive", "ja": "隅々に広がった 浸透する 充満する" },
      { "en": "ubiquitous", "ja": "至る所にある" },
      { "en": "deduce", "ja": "を推測する 演繹する" },
      { "en": "simulate", "ja": "を模擬実験する を装う をまねる" },
      { "en": "merge", "ja": "を 合併する を融合させる 溶け込む" },
      { "en": "penetrate", "ja": "に 浸透する に 進出する を 貫く を 見抜く" },
      { "en": "cater", "ja": "の 料理をまかなう 要望などに 応える" },
      { "en": "assault", "ja": "に暴行する を攻撃する" },
      { "en": "torture", "ja": "を拷問にかける を苦しめる" },
      { "en": "bleed", "ja": "出血する" },
      { "en": "erect", "ja": "を建てる を直立させる" },
      { "en": "cherish", "ja": "を大切にする を心に抱く" },
      { "en": "arouse", "ja": "感情など を引き起こす を目覚めさせる" },
      { "en": "doom", "ja": "通例受身形で 運命にある" },
      { "en": "mourn", "ja": "を 悼む を 嘆く" },
      { "en": "dread", "ja": "をひどく恐れる" },
      { "en": "nourish", "ja": "に栄養を与える をはぐくむ" },
      { "en": "inject", "ja": "人 に注射する を注入する を導入する" },
      { "en": "swear", "ja": "を ののしる を 誓う" },
      { "en": "bid", "ja": "に の値をつける 挨拶 を述べる" },
      { "en": "corrupt", "ja": "を堕落させる を買収する 堕落する" },
      { "en": "preoccupy", "ja": "の心を奪う を夢中にさせる" },
      { "en": "browse", "ja": "を 拾い読みする を 閲覧する 商品など を見て歩く" },
      { "en": "compile", "ja": "を編集する 資料など をまとめる" },
      { "en": "allocate", "ja": "を割り当てる 分配する" },
      { "en": "offset", "ja": "を相殺する 埋め合わせる をオフセット印刷にする" },
      { "en": "restrain", "ja": "を制止する を規制する" },
      { "en": "comply", "ja": "従う 応じる" },
      { "en": "expire", "ja": "期限が切れる" },
      { "en": "embark", "ja": "に 乗り出す 乗船 搭乗 する" },
      { "en": "flap", "ja": "パタパタ動く 羽ばたく をパタパタ動かす" },
      { "en": "furnish", "ja": "に を 備えつける" },
      { "en": "forge", "ja": "を偽造する 関係など を築く を鍛造する" },
      { "en": "thrust", "ja": "を押しつける を突き刺す 押し進む" },
      { "en": "dispatch", "ja": "を派遣する を発送する を処理する" },
      { "en": "resent", "ja": "に憤慨する" },
      { "en": "reconcile", "ja": "を と 一致させる を和解させる" },
      { "en": "allege", "ja": "を主張する" },
      { "en": "oppress", "ja": "を抑圧 迫害 する を悩ませる" },
      { "en": "expel", "ja": "を追放する を吐き出す" },
      { "en": "ascend", "ja": "を 上がる" },
      { "en": "commence", "ja": "始まる を開始する し始める 仕事 作業 を始める" },
      { "en": "advent", "ja": "出現 到来" },
      { "en": "reign", "ja": "治世 統治" },
      { "en": "diplomacy", "ja": "外交 的手腕" },
      { "en": "embassy", "ja": "大使館 大使一行" },
      { "en": "exile", "ja": "亡命 者 国外 追放" },
      { "en": "refuge", "ja": "避難 所 保護" },
      { "en": "plight", "ja": "窮状 悪い 状態" },
      { "en": "solitude", "ja": "ひとりでいること 孤独" },
      { "en": "fallacy", "ja": "誤った考え 誤信 錯誤" },
      { "en": "latitude", "ja": "緯度 行動 思想などの 許容範囲" },
      { "en": "eclipse", "ja": "日食 月食などの 食 名声などの 失墜" },
      { "en": "basin", "ja": "流域 盆地 海盆 洗面器 台" },
      { "en": "erosion", "ja": "浸食 衰退" },
      { "en": "archaeology", "ja": "考古学" },
      { "en": "errand", "ja": "人の 使い 使い走り 用件" },
      { "en": "mercy", "ja": "慈悲 通例" },
      { "en": "a", "ja": "幸運" },
      { "en": "rhetoric", "ja": "修辞 法 美辞麗句" },
      { "en": "verse", "ja": "韻文 散文 詩" },
      { "en": "congestion", "ja": "混雑" },
      { "en": "sewage", "ja": "下水" },
      { "en": "complement", "ja": "の 補完物 補足 文法の 補語" },
      { "en": "subsidy", "ja": "補助金 報奨金" },
      { "en": "mortgage", "ja": "住宅ローン 抵当 権" },
      { "en": "attorney", "ja": "米 弁護士 代理人" },
      { "en": "outfit", "ja": "衣装一式 装備 道具 一式 組織" },
      { "en": "bulk", "ja": "の 大半 大きさ 大量" },
      { "en": "reunion", "ja": "再会 の集い 再結合" },
      { "en": "synthesis", "ja": "合成 総合" },
      { "en": "mold", "ja": "鋳型 鋳物 性格 かび" },
      { "en": "thirst", "ja": "のどの 渇き に対する 渇望" },
      { "en": "greed", "ja": "強欲" },
      { "en": "bribe", "ja": "賄賂" },
      { "en": "contempt", "ja": "軽蔑 恥辱" },
      { "en": "texture", "ja": "感触 手触り 本質 質感" },
      { "en": "orphan", "ja": "孤児" },
      { "en": "harassment", "ja": "嫌がらせ ハラスメント" },
      { "en": "hay", "ja": "干し草" },
      { "en": "doctrine", "ja": "教義 米 政策上の 主義" },
      { "en": "holistic", "ja": "全体論の 医療が ホリスティックの" },
      { "en": "liable", "ja": "しがちな を 受けやすい 責任がある" },
      { "en": "earnest", "ja": "まじめな 熱心な" },
      { "en": "intelligible", "ja": "簡単に 理解できる" },
      { "en": "abrupt", "ja": "突然の" },
      { "en": "reckless", "ja": "無謀な を 顧みない" },
      { "en": "furious", "ja": "激怒した 猛烈な" },
      { "en": "eloquent", "ja": "雄弁な 説得力のある" },
      { "en": "juvenile", "ja": "青少年の" },
      { "en": "notorious", "ja": "悪名高い" },
      { "en": "timid", "ja": "臆病な 内気な" },
      { "en": "humid", "ja": "湿気のある 蒸し暑い" },
      { "en": "contagious", "ja": "感染 性 の 病気を伝染する" },
      { "en": "cynical", "ja": "冷笑的な 皮肉な" },
      { "en": "dumb", "ja": "ばかげた 口のきけない 無言の" },
      { "en": "monotonous", "ja": "単調な" }
    ]
  },
  {
    "id": "audio_20",
    "name": "音声用セット 20 (1901 - 1906)",
    "words": [
      { "en": "perpetual", "ja": "永続的な ひっきりなしの" },
      { "en": "dizzy", "ja": "目まいがする 当惑した" },
      { "en": "weary", "ja": "疲れ果てた に うんざりした" },
      { "en": "numb", "ja": "麻痺した 無感覚な ぼう然とした" },
      { "en": "mortal", "ja": "致命的な 死すべき 運命の 不死の" },
      { "en": "zealous", "ja": "熱心な 熱狂的な" }
    ]
  }
];
